### PR TITLE
Improve rewriting functionality

### PR DESCRIPTION
**Pull request by zgrannan**
Improve rewriting functionality to fix many bugs and use the new REST algorithm described [here](https://www.cs.ubc.ca/~alexsumm/papers/Grannan21.pdf).

There is still some cleanup left to do, just creating this draft PR to test on CI.

### CODE REVIEW

**Comment by nikivazou** [comment]
Great! Thanks Zack! Is there a relevant fixpoint PR (did not see it)?

**Comment by zgrannan** [comment]
Just created the PR for fixpoint [here](https://github.com/ucsd-progsys/liquid-fixpoint/pull/497). It looks like there are some merge conflicts I need to fix first :/

**Comment by zgrannan** [comment]
@nikivazou Actually it looks like the current `develop` branch of this (liquidhaskell) repo points to an older version of `fixpoint`: https://github.com/ucsd-progsys/liquid-fixpoint/tree/98e36e9b73062355a6864022395d8207e85c9512, which was last updated about a month ago.

Should LiquidHaskell be updated to use the latest develop version of liquid-fixpoint?

**Comment by facundominguez** [comment]
There's a PR to do the update here: https://github.com/ucsd-progsys/liquidhaskell/pull/1881
But CI seems to be failing on it for unrelated reasons.

**Comment by facundominguez** [comment]
#1881 is merged and now liquidhhaskell points to the latest liquid-fixpoint. Cheers!

**Pull request merged**
