### PR TITLE
Dump logs of failed tests when running on Travis

### PR DESCRIPTION
**Pull request by spinda**
@nikivazou and I were discussing this earlier today. When a test fails on Travis, right now, we have to re-run it on our own systems to see log output. Besides being inconvenient, sometimes we have test failures on Travis that we can't reproduce ourselves. This PR modifies the test and Travis scripts to dump the logs of failed tests when running on Travis. It also tightens a few things up in the Travis script.

You can view an example here:

https://travis-ci.org/spinda/liquidhaskell/jobs/57744542#L832-L836

with this at the end:

```
(...)
The command "scripts/travis do_test "$TESTS" "$SMT" && scripts/travis test_source_pkg" exited with 1.
$ scripts/travis dump_fail_logs
./benchmarks/bytestring-0.9.2.1/Data/ByteString/Lazy/.liquid/Char8.hs.log.fail:
    http://sprunge.us/FQeJ
./benchmarks/bytestring-0.9.2.1/Data/ByteString/.liquid/Char8.hs.log.fail:
    http://sprunge.us/bhQT
```

I originally had the Travis script dump the logs to stdout, but their length caused Travis to break in strange ways. So I have the script upload them to the http://sprunge.us pastebin instead, printing out links to where the logs can be viewed.

### CODE REVIEW

**Comment by spinda** [comment]
Note that the Travis tests are *supposed* to fail here. `bytestring` is still broken on `master`; this shouldn't prevent the PR from being merged.

**Comment by nikivazou** [comment]
Thanks @spinda !

**Comment by nikivazou** [comment]
The log for `WhieM.hs` is not super useful: http://sprunge.us/BWGj

It seems that it just time-outs?

**Comment by spinda** [comment]
@nikivazou The `Killed` at the end indicates that something else is killing the process before it completes. Not sure what would be doing that...

**Comment by spinda** [comment]
Exit code 137 means that the process received SIGKILL. The test runner
isn't getting killed, so it can't be the Travis script, and there's nothing
that would kill the liquid process in the test runner.

Only thing I can come up with is that we're running out of memory and
Linux's OOM killer is killing liquid.

**Pull request merged**
