### PR TITLE
fix for #1267

### PR DESCRIPTION
**Pull request by nikivazou**
Strengthen the DEFAULT case with data con alternative checker info, if available.

### CODE REVIEW

**Comment by ranjitjhala** [comment]
Good idea! this basically says “default is NOT equal to one of the matched
patterns”right?

**Comment by nikivazou** [comment]
Yes. 

Still imprecise though... 

For instance, if I define a measure `isB`, LH does not know that `isB v <=> is$ModuleName.B`. 
So, it cannot automatically prove `isB x` after the cases where x is matched with B.
But I do not know how to make is more precise...

**Comment by ranjitjhala** [comment]
You mean there are extra facts that get put in the env when we do “full”
case expand, right?

**Comment by nikivazou** [comment]
Yes.

**Pull request merged**
