### PR TITLE
Remove function sorted binders 

### PR DESCRIPTION
**Pull request by nikivazou**
See #432

### CODE REVIEW

**Comment by ranjitjhala** [comment]
Looks like various tests failing?

**Comment by nikivazou** [comment]
Ok, most tests pass, so function binders can be removed from the environment!
There are some failing tests in vector-algorithms, but commit https://github.com/ucsd-progsys/liquidhaskell/commit/a74ce288b84fb0176066ea2321df6e39577a7a3a broke them

**Comment by ranjitjhala** [comment]
Don't know whats happening with vector-algos -- pretty sure I ran the tests
locally before merging but I guess I messed up. Will fix!

@nikivazou -- can you find which vector-algos tests break and add those as
an issue assigned to me? Thanks!

On Friday, September 11, 2015, Niki Vazou <notifications@github.com> wrote:

> Merged #452 <https://github.com/ucsd-progsys/liquidhaskell/pull/452>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquidhaskell/pull/452#event-407613284>.
>


-- 
Ranjit.

**Comment by nikivazou** [comment]
Done!

On Fri, Sep 11, 2015 at 4:30 PM, Ranjit Jhala <notifications@github.com>
wrote:

> Don't know whats happening with vector-algos -- pretty sure I ran the tests
> locally before merging but I guess I messed up. Will fix!
>
> @nikivazou -- can you find which vector-algos tests break and add those as
> an issue assigned to me? Thanks!
>
> On Friday, September 11, 2015, Niki Vazou <notifications@github.com>
> wrote:
>
> > Merged #452 <https://github.com/ucsd-progsys/liquidhaskell/pull/452>.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/ucsd-progsys/liquidhaskell/pull/452#event-407613284
> >.
> >
>
>
> --
> Ranjit.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquidhaskell/pull/452#issuecomment-139686211>
> .
>



-- 
Niki Vazou

**Pull request merged**
