### PR TITLE
Work around Travis issues with travis_retry

### PR DESCRIPTION
**Pull request by spinda**
Random network failures during Cabal dependency installs break Travis builds. Work around this by adding travis_retry to commands that install dependencies.

See #362.

### CODE REVIEW

**Comment by spinda** [comment]
I'm submitting this as a pull request first to make sure that `.travis.yml` is still valid after my changes, instead of potentially messing up builds on `master`.

**Comment by spinda** [comment]
I've added another workaround to prevent Travis from timing out tests that take > 10 minutes to complete.

**Comment by spinda** [comment]
This should be ready to merge now. I've split out the Travis code into a separate script and added some helper functions to work around the issues we've been running into.

**Comment by gridaphobe** [comment]
Cool, thanks @spinda!

**Pull request merged**
