### PR TITLE
Use identifiers unlikely to collide.

### LINKED ISSUE #1293: Cannot use 'y' as a name of a record field
If you have a record with a field named `y`, for example,

```haskell
module Foo where                                           
                                                                                
{-@ data Box = B { y :: Int } @-}                                           
data Box = B { y :: Int }
```

You will get the following error:

```console
LiquidHaskell Version 0.8.2.4
Copyright 2013-18 Regents of the University of California. All Rights Reserved.


**** DONE:  A-Normalization ****************************************************
 

**** DONE:  annotate ***********************************************************
 

**** RESULT: ERROR *************************************************************


 /home/ytaka23/Develop/liquid-test/.stack-work/install/x86_64-linux/lts-11.4/8.2.2/share/x86_64-linux-ghc-8.2.2/liquidhaskell-0.8.2.4/include/GHC/Base.spec:28:8: Error: Illegal qualifier specification for `Fst`
  
 28 | qualif Fst(v:a, y:b): (v = (fst y))
             ^
  
  
 Cannot unify (Tuple @(42) @(43)) with func(0, [Foo.Box; int]) in expression: fst Foo.y


 /home/ytaka23/Develop/liquid-test/.stack-work/install/x86_64-linux/lts-11.4/8.2.2/share/x86_64-linux-ghc-8.2.2/liquidhaskell-0.8.2.4/include/GHC/Base.spec:29:8: Error: Illegal qualifier specification for `Snd`
  
 29 | qualif Snd(v:a, y:b): (v = (snd y))
             ^
  
  
 Cannot unify (Tuple @(42) @(43)) with func(0, [Foo.Box; int]) in expression: snd Foo.y
```

On the other hand, after you change `y` to `x`, it works.

```haskell
module Foo where                                           
                                                                                
{-@ data Box = B { x :: Int } @-}                                           
data Box = B { x :: Int }
```

### PR DESCRIPTION
**Pull request by superfunc**
Not sure if this is the correct approach, so feel free to tell me if I'm off base :)

Fixes #1293

### CODE REVIEW

**Comment by superfunc** [comment]
Note that the CircleCI run failed for reasons unrelated to my change:

```
curl -SL https://www.stackage.org/stack/linux-x86_64-static | tar zx -C /tmp
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

100  4002  100  4002    0     0   1185      0  0:00:03  0:00:03 --:--:--  1234

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

curl -SL https://www.stackage.org/stack/linux-x86_64-static | tar zx -C /tmp returned exit code 2

Action failed: curl -SL https://www.stackage.org/stack/linux-x86_64-static | tar zx -C /tmp```

**Comment by ranjitjhala** [comment]
Awesome thanks! Will take a look soon!!!

**Comment by ranjitjhala** [comment]
Odd! Let me try rebuilding on circle!

**Comment by atondwal** [comment]
see : https://github.com/ucsd-progsys/liquidhaskell/pull/1310/commits/22a2493267c789ca3cf7c6023dcfd0550215cfcb

**Comment by superfunc** [comment]
It looks like that change isnt in develop, can we get that merged in?

**Comment by superfunc** [comment]
ping @ranjitjhala

**Comment by ranjitjhala** [comment]
Thanks for the ping! Will look at this and merge in today!

**Comment by ranjitjhala** [comment]
Sorry got caught up in stuff, first thing tomorrow!

**Comment by ranjitjhala** [comment]
Sorry for the delay here -- am hoping tests will pass and can merge in today!

**Comment by ranjitjhala** [comment]
Thanks @superfunc !!!

**Pull request merged**
