### PR TITLE
Windows 64 bit builds on AppVeyor

### PR DESCRIPTION
**Pull request by varosi**
Builds are creating valid Windows 64bit executables and are packed with all DLLs needed.
The current problem is this error on execution with a simple Haskell source file:

`liquid: C:\projects\liquidhaskell\.stack-work\install\a3f23259\share\x86_64-windows-ghc-8.6.4\liquidhaskell-0.8.6.0\include\CoreToLogic.lg: openFile: does not exist (No such file or directory)`

This is latest successful build:
https://ci.appveyor.com/project/varosi/liquidhaskell/builds/23492494

### CODE REVIEW

**Comment by varosi** [comment]
Windows tests pass:
https://ci.appveyor.com/project/varosi/liquidhaskell/builds/23519701

**Comment by ranjitjhala** [comment]
Thanks @varosi ! What do we need to do? 

1. Merge this PR
2. Re-enable APPVEYOR

anything else?

**Comment by varosi** [comment]
Yes, that's all. 
I'll think how to optimise building more. But current implementation at least build and run basic tests successfully.

**Comment by varosi** [comment]
Do you know what this means:
`liquid: C:\projects\liquidhaskell\.stack-work\install\a3f23259\share\x86_64-windows-ghc-8.6.4\liquidhaskell-0.8.6.0\include\CoreToLogic.lg: openFile: does not exist (No such file or directory)`

This is happening on running liquid.exe built on AppVeyor, but executed on different machine. Does it tries to search for CoreToLogic.lg file on that exact location? Could it be made so it searching it in current directory also? I think this could possibly happen in separate PR.

**Comment by varosi** [comment]
Possibly this have to become more dynamic:
```
getIncludeDir :: IO FilePath
getIncludeDir      = dropFileName <$> getDataFileName ("include" </> "Prelude.spec")
```

**Comment by ranjitjhala** [comment]
Thanks @varosi! am merging! will try to figure out how to re-enable the CI with appveyor...

**Comment by varosi** [comment]
Thanks for the merge! 
AppVeyor service is already setup, only this GitHub project have to be. I'll try to fix this path problem, so I could create a PR to test how system work.

**Pull request merged**
