### PR TITLE
Nicer syntax for Relational Types

### PR DESCRIPTION
**Pull request by oquechy**
Replace this:

```haskell
-- Syntax: 
-- term1 ~ term2 :: type1 ~ type2 ~~ predicate 

{-@ relational abs ~ abs :: x1:Int -> Int  ~ x2:Int -> Int 
                         ~~ 0 <= x1 && x1 < x2 => r1 x1 < r2 x2 } @-}
```

with this:

```haskell
-- Syntax: 
-- term1 ~ term2 :: { type1 ~ type2 | predicate }

{-@ relational abs ~ abs :: { x1:Int -> Int 
                            ~ x2:Int -> Int 
                            | 0 <= x1 && x1 < x2 :=> r1 x1 < r2 x2 } @-}

```

### CODE REVIEW

**Comment by nikivazou** [comment]
@oquechy great! You have pushed many empty files. Is it a mistake?

**Comment by oquechy** [comment]
@nikivazou oops, it’s a mistake. My relational branch has these tests and I tried to remove them from `develop` when merging. So they are supposed to be deleted, not empty 🤔

**Comment by oquechy** [comment]
I’ll fix it

**Comment by oquechy** [comment]
Done.

But I also had to fix a CI script hlint.yml. Otherwise hlint gave an error about a missing environment dependency. See the failing check 2 commits ago

**Comment by oquechy** [comment]
This was the error:

```
 /opt/hostedtoolcache/hlint/3.4/x64/hlint: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
```

In this CI run:
https://github.com/ucsd-progsys/liquidhaskell/actions/runs/3658515932/jobs/6183403526

**Comment by oquechy** [comment]
@nikivazou the bulid is fixed! I also added .DS_store to .gitignore.

**Pull request merged**
