### PR TITLE
Autosize

### PR DESCRIPTION
**Pull request by nikivazou**
Automatically infer sizing (termination) info for ADT: the user does not have to write the sizing functions.

### CODE REVIEW

**Comment by ranjitjhala** [comment]
Nice! Can you update the readme and change log?

**Comment by ranjitjhala** [comment]
Why is the build broken?

**Comment by gridaphobe** [comment]
Unused variables in `Language.Haskell.Liquid.Constraint.Generate` (https://travis-ci.org/ucsd-progsys/liquidhaskell/jobs/66142967#L1120-L1127)

**Comment by ranjitjhala** [comment]
I don't understand, how does it build locally then?

On Tue, Jun 9, 2015 at 7:53 PM, Eric Seidel <notifications@github.com>
wrote:

> Unused variables in Language.Haskell.Liquid.Constraint.Generate (
> https://travis-ci.org/ucsd-progsys/liquidhaskell/jobs/66142967#L1120-L1127
> )
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquidhaskell/pull/402#issuecomment-110568506>
> .
>



-- 
Ranjit.

**Comment by gridaphobe** [comment]
You're probably not using `-Werror` locally, so the unused variables would just present as a warning.

**Comment by ranjitjhala** [comment]
I'm just hitting "make" (and presumably so is Niki), and I think `-Werror`
happens by default in that case (its certainly happening to me, its caught
a bunch of little things which have made it worth the irritation)

(i.e. how would one even *not* use it locally given that its in the .cabal
file by default?)

​

**Comment by gridaphobe** [comment]
`-Werror` is excluded by default (https://github.com/ucsd-progsys/liquidhaskell/blob/master/liquidhaskell.cabal#L45-L48)

That's probably my fault as I have to disable it when I upload to hackage, and sometime accidentally commit the result..

**Comment by ranjitjhala** [comment]
! then how come I get it whenever I hit `make` ?
​

**Comment by ranjitjhala** [comment]
ah you can circumvent it with 'cabal install' instead of 'make'. tsk. tsk.
​

**Comment by ranjitjhala** [comment]
anyways, @nikivazou please fix the errors, the unused var thing is super
annoying, but also super useful (and on the whole positive IMO.)

​

**Comment by gridaphobe** [comment]
Also of note, `make` defaults to the first target which is

```
fast:
	$(CABAL) install -fdevel --ghc-options=$(FASTOPTS)
```

the `-fdevel` turns on `-Werror` regardless of defaults.

**Comment by nikivazou** [comment]
So, I am doing `cabal install` and I had this issue before (building locally and then failing on travis). I remember I turned on `-Werror` then. Lets keep the flag on always.

**Pull request merged**
