### PR TITLE
patch the 7.10 desugarer because SourceNotes aren't providing enough data

### PR DESCRIPTION
**Pull request by gridaphobe**
@ranjitjhala the diff/patch idea worked quite well, only had a few small things to tweak

### CODE REVIEW

**Comment by gridaphobe** [comment]
```haskell
module Foo where

toDigits :: Integer -> [Integer]
toDigits n
        | n < 10        = [n]
        | otherwise = toDigits (n `div` 10) ++ [n `mod` 10]
```

this is the file i tested. `div` and `mod` are correctly annotated, but for some reason `++` is not... haven't investigated why yet.

**Comment by ranjitjhala** [comment]
1. any idea why travis is being difficult (build has STILL not finished?)
2. how can i try this locally?
​

**Comment by ranjitjhala** [comment]
I am going to merge this aggressively (since travis is being difficult...)

**Comment by gridaphobe** [comment]
@ranjitjhala well I just pushed a small fix about 15 min ago (idk why github thinks it was 4 hours ago..)

**Pull request merged**
