### PR TITLE
add Data.Maybe spec

### PR DESCRIPTION
**Pull request by renanroberto**
Added specs for some functions on `Data.Maybe` and two measures needed for the types. The most relevant being the type for `fromJust`, so now it can be type safe in the same way `head` is

### CODE REVIEW

**Comment by ranjitjhala** [comment]
Hi @renanroberto -- fantastic, looks like CI is happy. Can I make a small request: can you add tests, e.g. your own

in `tests/neg` 

```
foo :: Maybe a -> a
foo x = fromJust x
```

and in `tests/pos/`

```
{-@ foo :: {x:_ | isJust' x} -> a @-}
foo :: Maybe a -> a
foo x = fromJust x
```

Just to make sure that the new specs are getting used?

Thanks so much!

**Comment by renanroberto** [comment]
Done! Let's hope that the CI remains happy =D

**Comment by ranjitjhala** [comment]
Odd I’ll take a look tomorrow!

**Comment by renanroberto** [comment]
Ok. Let me know anything I can help

**Comment by renanroberto** [comment]
CI approved! :tada: 

I've noticed that we can use the already existing measure `isJust` instead of creating `isJust'`and `isNothing'`. I will make that change

**Review by ranjitjhala — APPROVED** [review]

**Comment by ranjitjhala** [comment]
Thanks @renanroberto !!!

**Pull request merged**
