### PR TITLE
add structural induction checks for termination metrics

### PR DESCRIPTION
**Pull request by nikivazou**
For #1198

### CODE REVIEW

**Comment by ranjitjhala** [comment]
Wow, awesome!!!

**Comment by nikivazou** [comment]
I have errors from programs similar to 

```
{-@ data LL [llen] @-} 

{-@ invariant {v:LL a | (llen v) >= 0} @-}

{-@ measure llen :: (LL a) -> Int 
    llen(N)      = 0
    llen(C x xs) = 1 + (llen xs)
  @-}
```

Since `llen` is a logic function but not a Haskell one. 
I will edit the programs similar to the above that generate an error: we are going towards to all logic functions should be defined in  Haskell, correct?

**Comment by ranjitjhala** [comment]
Yes, if possible!

(Is the error here that the default size is NOT defined by a core expr and
hence outside your new checker?)

**Comment by nikivazou** [comment]
The error is 
```
     Not in scope: variable or data constructor 'llen'
```

It is generated in Bare when I want to turn the symbol `llen` into a ghc `Var`...

**Comment by ranjitjhala** [comment]
Ah ok got it.

**Comment by ranjitjhala** [comment]
Only 32 failures v good! Thought there would be hundreds!

**Comment by ranjitjhala** [comment]
In short: all default sizes have to now be GHC vars, right?

**Comment by nikivazou** [comment]
I am fixing the tests. 

@ranjitjhala: why do I need to export all the Haskell functions that I declare as measures?

**Comment by ranjitjhala** [comment]
@nikivazou -- the measures (and reflects, inlines etc.) have to be 
exported because effectively `measure` is a **global name**. If you have:

```haskell
module A (func) where 

{-@ measure foo @-}
foo = ...

{-@ func :: ... uses `foo` in its type @-}
func = ...
```

and then you **import** `A` elsewhere, then we need to **resolve** 
the  name `foo` that appears in the signature for `A.foo` and for that, 
GHC requires that `foo` be exported from `A`.

**Comment by nikivazou** [comment]
This is because importing module `A` imports all measures of `A`. We should change that (if possible). I might import `A` but not all its measures...

BTW, now all my failing tests have to do with name resolution...........

**Comment by ranjitjhala** [comment]
1. Btw, maybe you can just issue a 

`WARNING: Measure 'bslen' not a GHC Variable, omitting structural well-foundedness check`

or similar for "legacy" measures that are not GHC variables?

2. I found out recently that you can rerun a subset of tests matching a pattern with:

```
stack test liquidhaskell --fast --test-arguments="-p Unit"
```

if you change, e.g. `-p Unit` to`-p ByteString` then it will just run those tests...

**Comment by ranjitjhala** [comment]
Yes, ideally we'd do that, but its very non-trivial, because unlike with
GHC,
where importing `foo` just imports `foo`, for us, we have to end up
importing
everything that appears (transitively) in the signature for foo...

**Comment by nikivazou** [comment]
The problem is that `lookupGhcVar` throws the ghc error, and I do not know of any way to catch it and emit the warming you are suggesting... 

Ok, will make yet another flag to deactivate the checks for BS & Text. 
Yet, now my errors in text* are 

```
 Data/Text/Internal.hs:69:13: Error: GHC Error

 69 | {-@ measure tlen @-}
                  ^

     Not in scope: variable or data constructor 'tlen'
```

because Internal exports the measure `tlen`, but my current module is not importing it... 
This is annoying

*Cannot run BS locally even with your suggestion... I am missing something...

**Comment by ranjitjhala** [comment]
ok, the flag is a reasonable workaround for now...I can then take a look.

**Comment by ranjitjhala** [comment]
Yay! Thanks @nikivazou!!

**Comment by nikivazou** [comment]
@ranjitjhala again text and bytestring reveal a name resolution mess, so if you want to give it a try, up to you :)

**Comment by ranjitjhala** [comment]
Sounds good : they work with your flag rigght?

**Comment by nikivazou** [comment]
They all work: merging!

**Pull request merged**
