### PR TITLE
Revert "Remove -Wno-name-shadowing from liquidhaskell"

### PR DESCRIPTION
**Pull request by facundominguez**
Reverts ucsd-progsys/liquidhaskell#1967

CI was green, but we discovered since then a bug in the test framework and this PR introduced some failures inadvertently.

### CODE REVIEW

**Comment by facundominguez** [comment]
@tbidne, do you want to give splitting the PR a try?

[This is the issue](https://github.com/ucsd-progsys/liquidhaskell/issues/1995) with more details of the breakage.

**Comment by tbidne** [comment]
@facundominguez Will do. Sorry about that!

**Comment by michaelborkowski** [comment]
Some more details on a similar error I've been getting -- I think it's the same thing as the bug in CI in issue #1995.  LiquidHaskell no longer is recognizing a variable bound in a `where` block when used in an annotation inside the where block.

My error has disappeared now that PR #1967 has been reverted. 

Here's the relevant definition of a function in my project:
```
{-@ makeWFFT :: g:FEnv -> { t:FType | Set_sub (ffreeTV t) (bindsF g) }
                       -> { k:Kind  | isWFFT g AEmpty t k } -> ProofOf(WFFT g t k) / [ftsize t, ksize k] @-}
makeWFFT :: FEnv -> FType -> Kind -> WFFT
.....
makeWFFT g (FTPoly k   t) Star = WFFTPoly g k t Star nms mk_wf_t
  where
    {-@ mk_wf_t :: { a:Vname | NotElem a nms } -> ProofOf(WFFT (FConsT a k g) (unbindFT a t) Star) @-}
    mk_wf_t a = makeWFFT (FConsT a k g) (unbindFT a t)
                         (Star ? lem_isWFFT_unbindFT g AEmpty 0 k t Star a)
    nms = unionFEnv [] g
```

This results in the following error:

```
/home/michael/liquidmeta/icfp22-submission/src/SystemFWellFormedness.hs:180:20: error:
    • Illegal type specification for `mk_wf_t`
    mk_wf_t :: a:{VV##0 : [GHC.Types.Int](http://ghc.types.int/) | not (Set_mem VV##0 (listElts nms))
                                          && VV##0 >= 0} -> {proofObj : SystemFWellFormedness.WFFT | propOf proofObj == Basics.WFFT (Basics.FConsT a k g) (Basics.unbindFT a t) Basics.Star}
    Sort Error in Refinement: {VV##0 : int | not (Set_mem VV##0 (listElts nms))
                                             && VV##0 >= 0}
    Unbound symbol nms --- perhaps you meant: len, snd, fst ?
    Just
    •
    |
180 |     {-@ mk_wf_t :: { a:Vname | NotElem a nms } -> ProofOf(WFFT (FConsT a k g) (unbindFT a t) Star) @-}
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by ranjitjhala** [comment]
Thanks for identifying and catching this Facundo!!!

**Pull request merged**
