### PR TITLE
Update CI to build with ghc 8.10.7

### PR DESCRIPTION
**Pull request by facundominguez**
Companion PR of https://github.com/ucsd-progsys/liquid-fixpoint/pull/501

### CODE REVIEW

**Comment by facundominguez** [comment]
All green!

**Comment by nikivazou** [comment]
Owowow that is great! 
So, LH is not compatible with ghc-8.10.7 and we can just make a new release?
We generally follow the same version numbers as ghc (https://github.com/ucsd-progsys/liquidhaskell/blob/develop/liquidhaskell.cabal#L3)

**Comment by facundominguez** [comment]
> So, LH is not compatible with ghc-8.10.7 and we can just make a new release?
> So, LH is **now** compatible with ghc-8.10.7 and we can just make a new release?

I have no objections. :)

**Comment by ranjitjhala** [comment]
😅 the “not” had me puzzled for a bit

**Pull request merged**
