### PR TITLE
Add Typing rule for `>>=`

### PR DESCRIPTION
**Pull request by gridaphobe**
to avoid creating a kvar for the lambda

### CODE REVIEW

**Comment by ranjitjhala** [comment]
Do the tests pass? (My version is similar but is failing tests due to some odd shadowed binder issue)

**Comment by gridaphobe** [comment]
I had a similar shadowing issue, it seemed to be due to calling
'normalize' on the lambda body rather than 'stitch'.
 
It looks like there are still a few failing tests, but I haven't looked
at them yet.

**Comment by ranjitjhala** [comment]
Yes, thought that might be it.

The icfp15 monad tests should fail with this ...

**Comment by ranjitjhala** [comment]
*Don't merge* -- I have taken the relevant parts into the `patterns` branch which also has some other stuff that I will send a PR for in due course.

**Pull request closed without merging**
