### PR TITLE
Make Native (i.e. new Haskell) solver the Default

### PR DESCRIPTION
**Pull request by ranjitjhala**
1. Use `--extSolver` if you really want to use the OCaml solver.
2. There are a few benchmarks (Data/Text/Fusion.hs, DBMovies.hs) 
    that require the above, see issues mentioning `Pair0.hs` and `Pair00.hs`.

### CODE REVIEW

**Comment by ranjitjhala** [comment]
Can someone else merge this and let me know ASAP.

**Comment by nikivazou** [comment]
I resolved the merge conflicts. Should Travis run it first?

**Comment by gridaphobe** [comment]
Can we add the `--extSolver` flag to the failing test cases (`LambdaDeBruijn` and `Data.Text.Fusion`)?

**Comment by nikivazou** [comment]
I am properly fixing these two right now

**Comment by ranjitjhala** [comment]
Yes, all tests _should_ pass (locally) and on travis, ideally after pair00
etc. are moved back into tests/pos.


On Tuesday, November 3, 2015, Niki Vazou <notifications@github.com> wrote:

> I am properly fixing these two right now
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquidhaskell/pull/504#issuecomment-153561622>
> .
>


-- 
Ranjit.

**Comment by nikivazou** [comment]
All tests pass, including the pair0[0]!!!

**Pull request merged**
