### PR TITLE
First two chapters of SF.

### PR DESCRIPTION
**Pull request by notcome**
I have partially ported proofs (given or exercises) into Liquid Haskell. The “partial” is to avoid unnecessary repetition.

### CODE REVIEW

**Comment by ranjitjhala** [comment]
@notcome -- Thanks! It looks like `sf/Induction.hs` and `sf/Basics.hs` are failing on CI can you see whats going on?

**Comment by notcome** [comment]
I suspect this is due to that I didn’t add an `--exact-data-con` option. A new version is updated.

**Comment by ranjitjhala** [comment]
Hmm. but then how did it work for you locally?

​

**Comment by notcome** [comment]
I just run liquid with `liquid --exact-data-con` every time. It is just an upper arrow key thing, so I can stay lazy. The new version contains the `{-@ LIQUID "--exact-data-con" @-}` at the top of each file.

**Comment by ranjitjhala** [comment]
ah, ok :-)

**Comment by ranjitjhala** [comment]
:Tara:

**Comment by ranjitjhala** [comment]
:tada:

**Pull request merged**
