### PR TITLE
Fix Circle CI tests

### PR DESCRIPTION
**Pull request by alanz**
See https://circleci.com/gh/alanz/liquidhaskell/132

### CODE REVIEW

**Comment by atondwal** [comment]
Huh. Any idea why not pulling in the fixpoint PRs fixes Data.Text?

**Comment by alanz** [comment]
Nope, I just commented out the thing that was blocking progress and saw what happened.

I have no insight as to why that line is there, or what it does.

**Comment by ranjitjhala** [comment]
Thanks @alanz!!!

**Comment by atondwal** [comment]
So this was just circle being silly: I just rebuilt the failing commit and it worked: https://circleci.com/gh/ucsd-progsys/liquidhaskell/1748

**Comment by atondwal** [comment]
I want us to *keep* the above line, because otherwise circle will failing matching LH/LF pull requests unless the LF pull request is already merged into `develop`

**Comment by alanz** [comment]
Hmm. Possibly I had a stale history on my circle instance. Sorry.

But all the tests passed with that line out?

**Pull request merged**
