### PR TITLE
add mutable boxed vector, work in progress

### PR DESCRIPTION
**Pull request by andrewthad**

### CODE REVIEW

**Comment by andrewthad** [comment]
This is currently a work in progress. It's my first time creating a spec file. Is there any way to type check what I've done so far so that I could if I messed anything up?

**Comment by nikivazou** [comment]
Thanks @andrewthad! Looks like `tests/pos/kmpVec.hs` is crashing. Do you know why? 

Circle https://circleci.com/gh/ucsd-progsys/liquidhaskell/877 is a good way to check that you did not mess up anything (or you can locally run `stack test liquidhaskell`). 
Also would be great if you added a test file that uses your specs.

**Comment by nikivazou** [comment]
BTW, (since it is not obvious) after you update a file in the include directory, you need to run `stack install` for the tests to use your updated specs.

**Comment by andrewthad** [comment]
@nikivazou Thanks! I'm currently building the test suite so that I can run it locally, which will hopefully give a more helpful error message than

    Wrong exit code
    expected: ExitSuccess
    but got: ExitFailure 2

I'm guessing that I have a syntax error somewhere in there.

**Comment by nikivazou** [comment]
You can just run `liquid tests/pos/kmpVec.hs` to see the error, the rest tests are OK!

**Comment by andrewthad** [comment]
That speeds thing up a lot. When I run that, I get this (I cut out some of the newlines):

    $ stack install
    ... some executables are copied to /home/andrew/.local/bin by stack
    $ /home/andrew/.local/bin/liquid tests/pos/kmpVec.hs
    LiquidHaskell Copyright 2009-15 Regents of the University of California. All Rights Reserved.
    **** DONE:  annotate ***********************************************************
    **** RESULT: ERROR *************************************************************
    Invalid Source

     /home/andrew/Development/liquidhaskell/tests/pos/kmpVec.hs:7:8-18: Error: GHC Error
     7 | import Data.Vector
                ^^^^^^^^^^^
         Could not find module ‘Data.Vector’
    Perhaps you meant Data.Functor (from base-4.8.2.0)
    Use -v to see a list of the files searched for.

     /home/andrew/Development/liquidhaskell/tests/pos/kmpVec.hs:8:8-26: Error: GHC Error
     8 | import Data.Vector.Mutable (write)
                ^^^^^^^^^^^^^^^^^^^
         Could not find module ‘Data.Vector.Mutable’
    Use -v to see a list of the files searched for.

So I don't think `liquid` is seeing the `vector` package correctly

**Comment by andrewthad** [comment]
Wait. I've had this issue before. I think I know the solution.

**Comment by andrewthad** [comment]
Weird. When I do `stack exec liquid tests/pos/kmpVec.hs`, it completes without any errors.

**Comment by nikivazou** [comment]
Surprising... maybe you do not have the updated include file? 

The circle error is this 

https://877-5913967-gh.circle-artifacts.com/0//tmp/circle-junit.XDudiY3/tasty/log/tests/pos/kmpVec.hs.log.fail

Namely, at line 29 of your spec file you bind the result of the type signature with an `r`, which is a parsing error.  (results cannot be bound to binders, only arguments are allowed to)

**Comment by andrewthad** [comment]
To reproduce the error locally, had to run:

    stack exec liquid -- -i include tests/pos/kmpVec.hs

Now I'm getting the same error that you pointed out. I'll fix this.

**Comment by andrewthad** [comment]
I believe I've fixed the errors that were showing up before. Even if it passes, don't merge this yet because I would like to add some more assumptions in a while.

**Comment by ranjitjhala** [comment]
Thanks @andrewthad & @nikivazou -- and sorry for the unfortunate parsing glitch (I think @gridaphobe or I tried to solve this one earlier but were stumped. Perhaps the new issue #788 will help to fix it properly.)

**Comment by ranjitjhala** [comment]
Yikes, just realized this was a PR against `master` and not `develop`... 
Whats the right protocol here? @andrewthad can I trouble you to 
re-submit the PR for `develop`? Sorry about this!

**Comment by ranjitjhala** [comment]
I just reverted this as I also saw the note about WIP. Sorry about that @andrewthad !

**Comment by andrewthad** [comment]
Ah, I didn't realize there was a develop branch. I'll PR against develop.

**Pull request merged**
