### PR TITLE
Gradual eliminate

### PR DESCRIPTION
**Pull request by nikivazou**

### CODE REVIEW

**Comment by ranjitjhala** [comment]
eee.. i hope this doest depend on the fixpoint merge which is still TBD?

**Comment by nikivazou** [comment]
I haven't merged in develop yet, but I would like to :)

**Comment by ranjitjhala** [comment]
​Sure, can you let me know the status though? there were a bunch of PRs and
I couldn't quite tell if you had addressed those issues or not?​

**Comment by nikivazou** [comment]
The active pull requests are the gradual branches on liquid haskell and fixpoint.

**Pull request merged**
