### PR TITLE
Refactor name resolution to use `Either` / `Diagnostics` 

### PR DESCRIPTION
**Pull request by ranjitjhala**
A partial step towards fixing #1773 

We want to at least error-out gracefully instead of a GHC panic due to a random exception.

### CODE REVIEW

**Comment by ranjitjhala** [comment]
@nikivazou lmk if you want to go over this -- it is a super tedious PR that refactors a bunch of "pure" code to use `Either` (aka `Bare.Lookup`) to not crash in the middle of name resolution.

**Comment by ranjitjhala** [comment]
Hi @yiyunliu and @jprider63 -- can you also take a quick look at this? In particular, is it going to mess  up stuff with the `class` PR?

**Comment by yiyunliu** [comment]
I'll take a look at around 4pm today. I don't think it would break anything
because I didn't really modify the existing resolution code (except for the
extra allowTypeclass boolean flag). I'll check to make sure.

**Comment by jprider63** [comment]
Didn't we modify name resolution in refinements so that GHC will desugar typeclasses for us? 

FYI we're meeting tomorrow morning to discuss merging the typeclass updates.

**Comment by yiyunliu** [comment]
The ghc elaboration is a separate pass. It could have been used to replace
the original LH resolution but I kept the old one and used ghc to type
check the refinements with symbols already resolved by LH. This should make
the type class extension compatible with the edits to the symbol resolution
code.

**Pull request merged**
