### PR TITLE
Make sure GHC versions match

### PR DESCRIPTION
**Pull request by spinda**
This should fix the issue described in #612.

I haven't actually verified that this detects the error case correctly&mdash;could someone help with that?

### CODE REVIEW

**Comment by gridaphobe** [comment]
I think the trick is to `stack install` this branch and then `stack exec liquid` in a project with a different version of ghc.

**Comment by ranjitjhala** [comment]
So shall we merge this?

**Comment by spinda** [comment]
No, after testing it needs some more work.

**Comment by nikivazou** [comment]
Closing this :(

**Pull request closed without merging**
