### PR TITLE
AppVeyor Windows CI builds support

### PR DESCRIPTION
**Pull request by varosi**
At ICFP 2018 I have promised to @nikivazou a Windows CI. Here it is.

Note: there is a file benchmarks/wouter-swierstra-xmonad-7715ec2/src/Aux.v that Windows doesn't like for some reason and GIT checkout doesn't succeed. I don't know what to do about it, but I'll try more attempts following days. It would be great if GitHub account for LiquidHaskell is setup so it does not allow for pull requests to be merged without passed this CI builds. This will guarantee future support for Windows invariant after any changes. This is done from GitHub project Settings | Branches | Add Rule | choose a branch and set require status checks on continuous-integration/appveyor/branch.

### CODE REVIEW

**Comment by varosi** [comment]
For my test environment (AppVeyor linked to my GitHub account) it is working:
https://ci.appveyor.com/project/varosi/liquidhaskell

**Comment by ranjitjhala** [comment]
Wow, this is awesome @varosi ! 

That xmonad file can simply be deleted -- its not needed for LH at all. Does that help?

**Comment by varosi** [comment]
Yes, that helps. I have deleted it in this branch/pull request. 
I have disabled testing (only builds), because a lot of tests were failing. Do you think that tests should be enabled for this pull request or this could be made in separate one?

**Comment by varosi** [comment]
@ranjitjhala, could you try to enable AppVeyor for liquidhaskell repo so we try that it work here for this pull request?

**Comment by piyush-kurur** [comment]
By the way the windows has a long file name problem that has hit me many times when using appveyor.
There is a limit of 260 character size and I run into it often. See for example the discussion around the following pull request https://github.com/raaz-crypto/raaz/pull/376

**Comment by ranjitjhala** [comment]
@varosi -- I _think_ I enabled appveyor -- can you check and confirm? (or let me know if something else needs to be done?) Thanks!

@piyush-kurur -- thanks for the heads up! I was not aware of this issue!

**Comment by varosi** [comment]
Seems like it's working, but CircleCI is giving this error for that pull request:

>   404  Not Found
> 
> Err http://ppa.launchpad.net precise/main amd64 Packages
>   404  Not Found
> 
> Err http://ppa.launchpad.net precise/main i386 Packages
>   404  Not Found
> 
> Ign http://ppa.launchpad.net precise/main Translation-en_US
> 
> Ign http://ppa.launchpad.net precise/main Translation-en
> 
> Fetched 7,954 kB in 10s (744 kB/s)
> W: GPG error: https://apt.dockerproject.org ubuntu-precise Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F76221572C52609D
> W: Failed to fetch http://ppa.launchpad.net/pdoes/ppa/ubuntu/dists/precise/main/source/Sources  404  Not Found
> 
> W: Failed to fetch http://ppa.launchpad.net/pdoes/ppa/ubuntu/dists/precise/main/binary-amd64/Packages  404  Not Found
> 
> W: Failed to fetch http://ppa.launchpad.net/pdoes/ppa/ubuntu/dists/precise/main/binary-i386/Packages  404  Not Found
> 
> E: Some index files failed to download. They have been ignored, or old ones used instead.
> 
> sudo apt-get -y update returned exit code 100

**Comment by piyush-kurur** [comment]
@varosi @ranjitjhala it looks like all your problems on windows (including the ones you have linked from here) might boil down to the use of long file paths (268 is the limit). It is a terrible bug to solve 
for someone who does not really use windows. It was @Mistuke who first pointed it out to me first 
and I have been bitten by it on and off.

If you just want to get your Appveyor builds running, you can try shortening the file names involved. 
In my case, I changed the clone directory to `c://r`  (instead of `c://raaz`) and the build directory to `d` (instead of `dist-newstyle`). This might  get Appveyor running but  a windows user will still have problems. 
There is some pending work by @Mistuke that is meant to be merged in ghc and/or cabal but I do
not know its status.

**Comment by varosi** [comment]
@piyush-kurur I have overcome problems with long file paths. CircleCI is Linux build, not Windows one.

**Comment by varosi** [comment]
@ranjitjhala Could you rerun CiricleCI build? Do you know something about the errors there?

**Comment by ranjitjhala** [comment]
Yes, let me try to rerun that build.

**Comment by ranjitjhala** [comment]
@varosi -- is it possible you "rebase" your PR against the latest develop? 
I *think* we updated the Circle CI scripts (since circle moved to version 2.0)
and I suspect the issues we're seeing are because your PR is using the old 
circle scripts?

**Comment by varosi** [comment]
I don't know, but I'll check how could it be done.

**Comment by nikivazou** [comment]
@varosi are you still on this PR or should we close it for now?

**Comment by varosi** [comment]
I'm here and I'll try to run latest LiquidHaskell on AppVeyor.

**Comment by varosi** [comment]
There is a regression in GHC 8.6.3 which is fixed in 8.6.4 for Windows. See https://www.haskell.org/ghc/blog/20190305-ghc-8.6.4-released.html

Currently I found that 32bit GHC 8.6.4 binaries are missing, so I filed an issue - https://github.com/commercialhaskell/stack/issues/4662

We have to wait a little bit so FP Complete people upload 32bit GHC.

Currently here you could see my successful build with GHC 8.6.3:
https://ci.appveyor.com/project/varosi/liquidhaskell/builds/23381710

but resulting binaries are not runnable on Windows.

**Comment by varosi** [comment]
Intermediate update:
I made it work with LTS-13.11 (GHC-8.6.4) on x64 up to some point, but now I hit AppVeyor unpaid restrictions to 1 hour build time. On 32bit version it's much faster to build, but there is not yet a GHC-8.6.4 on Stack servers for it.

**Comment by nikivazou** [comment]
How about if we tell it to only run the micro benchmarks? That should be faster
Otherwise, we wait!

**Comment by varosi** [comment]
Currently we're not running any benchmarks or tests. Just builds. I have success with x64 builds. I just have to add some DLLs and we're ready with builds. 
I remember that there were tests that didn't worked. I'll try to run them to see how much time they will run.

**Comment by varosi** [comment]
Another optimisation could be to cache GHC and libraries, which is doable.

**Comment by varosi** [comment]
Added here:
https://github.com/ucsd-progsys/liquidhaskell/pull/1442

**Comment by ranjitjhala** [comment]
btw, to run just some of the smaller tests, you can do:

   stack test liquidhaskell --fast --test-arguments "-p Micro"

**Comment by varosi** [comment]
Passed!
https://ci.appveyor.com/project/varosi/liquidhaskell/builds/23519701

**Comment by ranjitjhala** [comment]
Outstanding!! thanks so much @varosi!

What do we need to do?

1. Merge this PR
2. Re-enable APPVEYOR

anything else?

**Comment by varosi** [comment]
Better merge that one - https://github.com/ucsd-progsys/liquidhaskell/pull/1442

**Pull request closed without merging**
