### PR TITLE
Added version requirements to all cabal entries

### PR DESCRIPTION
**Pull request by christetreault**
_it builds on my machine!_

### CODE REVIEW

**Comment by christetreault** [comment]
Don't merge this yet, I'm still working on the readme. I just want travis to run its tests.

**Comment by christetreault** [comment]
OK, this is ready now. Please merge this when you get a chance!

**Comment by nikivazou** [comment]
Thanks!

**Comment by bmcfluff** [comment]
@christetreault How did you choose those version numbers? Some are newer than the newest lts release on Stackage...

**Comment by christetreault** [comment]
I chose those based on what cabal chose to install for cabal 1.18/GHC 7.8.4 and cabal 1.22/GHC 7.10.2. I don't use stack or stackage, so I don't know anything about that. That said, it seems to me that the idea is to have the widest bounds possible where you still know it works, so I don't see that to be an issue. Stackage should just install an older version, right?

That said, I just got something working, if it's broken for stackage, feel free to widen the bounds so it builds.

**Pull request merged**
