### PR TITLE
Pull updates to master into refactor-ref

### PR DESCRIPTION
**Pull request by christetreault**
Allright, time's up, let's do this.

### CODE REVIEW

**Comment by ranjitjhala** [comment]
Oops thought you did this already ... Please go ahead!

**Comment by nikivazou** [comment]
Travis cannot built it :( but it seems to be related with the fixpoint updates.

**Comment by christetreault** [comment]
Travis hasn't been able to build anything for quite a while it seems :(

**Comment by nikivazou** [comment]
Did you update the fixpoint-submodule?

**Pull request merged**
