### PR TITLE
Strings

### PR DESCRIPTION
**Pull request by nikivazou**
Replace unpack with untyped equality

### CODE REVIEW

**Comment by gridaphobe** [comment]
@nikivazou I think I've fixed the problems with travis on master, can you rebase?

**Comment by nikivazou** [comment]
Thanks @gridaphobe, lets see if it is succeeds now.

**Comment by ranjitjhala** [comment]
Did you see the issue by @lcycon ? There was some mention of CHAR and BYTESTRING which makes me wonder if it is related to strings...

**Comment by nikivazou** [comment]
I haven't seen it yet. Will take a look asap

**Pull request merged**
