### PR TITLE
Fix typos in README

### PR DESCRIPTION
**Pull request by stefkin**

### CODE REVIEW

**Comment by nikivazou** [comment]
Thanks so much @stefkin! Appreciate it! 
Can you please update your target branch to be `ucsd-progsys:develop` because for stability reasons we have made merging to master difficult:)

**Comment by ranjitjhala** [comment]
Thanks a lot for this!

Btw @nikivazou or @gridaphobe is there a way to make develop the default
for PR? Or at least maybe we should create a small CONTRIBUTING.md that
says as much?

**Comment by nikivazou** [comment]
Good point @ranjitjhala! I made develop the default branch

**Comment by stefkin** [comment]
re-created on develop branch in #811

**Pull request closed without merging**
