### PR TITLE
Phadej ghc 8.4

### PR DESCRIPTION
**Pull request by ranjitjhala**
This PR moves LH to GHC 8.4 (thanks to @phadej -- cf #1330)

However, it is also a significant _refactor_ of `Bare`, specifically, deleting `BareM` and all the inscrutable global dependencies that it wrought.

Not ready to merge yet.

- [x] asserted-sigs
- [x] unqualified imports
- [x] assumed-sigs
- [x] alias
- [x] importing
- [x] measures
- [x] importing
- [x] invariants
- [x] importing
- [x] holes
- [x] reflect / PLE
- [x] importing
- [x] datacon
- [x] importing
- [x] class/instance measures (len)
- [x] absref
- [x] class-refinements
- [x] lifted-bounds
- [x] termination
- [x] auto-size
- [x] source-spans 
- [x] error-messages

Current Score (*9/12/2018*)

Only the following tests fail:

Fixpoint-apply-unknown-sort
- [ ] tests/todo-rebare/T1089b.hs  [RJ]

Mystery
- tests/todo-rebare/DataKinds.hs [NV]

CLASS
- tests/todo-rebare/NatClass.hs [NV]
- tests/todo-rebare/VerifiedMonoid_NEG.hs [NV]
- tests/todo-rebare/VerifiedMonoid_POS.hs [NV]
- tests/classes/neg/Inst01.hs [NV]

### CODE REVIEW

**Comment by ranjitjhala** [comment]
Current score **no-bench** and **no-error**

```
Fri Aug 17 02:30:45 PDT 2018

rjhala@goto ~/r/s/l/liquidhaskell (phadej-ghc-8.4)> ack "OK" nohup.out  | wc
    862    2588   40670
rjhala@goto ~/r/s/l/liquidhaskell (phadej-ghc-8.4)> ack "FAIL" nohup.out  | wc
    177     540    8719
```

```

**Comment by phadej** [comment]
What I have started :O

**Comment by ranjitjhala** [comment]
haha, no worries -- its just prompted a _long_ needed cleanup!

**Comment by ranjitjhala** [comment]
@nikivazou -- this PR is close to being done -- I still have to 

1. remove the billion `tracepp` calls all over,
2. fix some tests (listed above). 

However, I will probably leave the ones marked `CLASS` above 
for you to deal with. 

However, it may be a good idea for you to try this branch out 
on any code you have outside the regression tests since it is 
quite a significant change:

1. The name resolution code is totally rewritten (for better and worse...)
2. Now if you are checking a bunch of modules and `Bar` imports `Foo`, 
    _must_ run liquid on `Foo` first, or it will complain.

Anyways, you may find other issues that I am missing, and it would be good 
to know about them _before_ merging this into `develop` :-)

**Comment by ranjitjhala** [comment]
@nikivazou this is _very_ close to merging. 

I am going to remove the billion `tracepp` 

scattered all over and then merge. 

Better try it against your benchmarks soon :-)

**Comment by phadej** [comment]
@ranjitjhala FWIW, the dependencies are slowly but steadily catching up with GHC-8.6.1, so I might make another PR(s) after this is merged. (I'd probably wait for GHC-8.6.2 to come out first)

**Comment by ranjitjhala** [comment]
@phadej that would be great! Since stuff is relatively fresh in my mind, it should be possible to make that upgrade soon too!

**Comment by ranjitjhala** [comment]
Here goes!

**Pull request merged**
