### PR TITLE
Make warnings more stringent and fix them

### PR DESCRIPTION
**Pull request by gridaphobe**

### CODE REVIEW

**Comment by ranjitjhala** [comment]
@gridaphobe what does this do?

**Comment by gridaphobe** [comment]
It just adds a few extra warnings about eg redundant or unused imports, and updates our various PPrint instances in LH to use the pprintTidy method.

**Comment by ranjitjhala** [comment]
btw, i have noticed that somehow the `pprint` has started rendering UF
applications
without a blank between the function and arg, i.e. `lenVV` instead of `len
VV` ...

​

**Comment by gridaphobe** [comment]
That should be fixed in develop, perhaps it was just missing an updated LF?

**Comment by ranjitjhala** [comment]
let me check... (definitely broken in master)

**Comment by gridaphobe** [comment]
ah, master is out of date, hence the PR

**Comment by ranjitjhala** [comment]
Just merged the PR (I thought) but `git pull origin master` did nothing...

**Comment by ranjitjhala** [comment]
Ugh. I foolishly merged PR 624 without doing 623 and now the latter is
fussing...

**Pull request merged**
