### PR TITLE
Axioms

### PR DESCRIPTION
**Pull request by nikivazou**
Use external haskell logical prover (added as a submodule) to automatically prove my axioms

### CODE REVIEW

**Comment by nikivazou** [comment]
All tests pass here. Can I merge? I am still playing with axiomatizations of functions but I added a new submodule `prover` that does all the solving.

**Comment by ranjitjhala** [comment]
where is the prover repo?

On Tue, Nov 17, 2015 at 9:00 AM, Niki Vazou <notifications@github.com>
wrote:

> All tests pass here. Can I merge? I am still playing with axiomatizations
> of functions but I added a new submodule prover that does all the
> solving.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquidhaskell/pull/513#issuecomment-157432818>
> .
>



-- 
Ranjit.

**Comment by nikivazou** [comment]
In my github 

https://github.com/nikivazou/prover

**Comment by ranjitjhala** [comment]
I just forked it to ucsd-progsys. Can you update the relevant links in the
PR?


On Tue, Nov 17, 2015 at 9:50 AM, Niki Vazou <notifications@github.com>
wrote:

> In my github
>
> https://github.com/nikivazou/prover
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquidhaskell/pull/513#issuecomment-157451231>
> .
>



-- 
Ranjit.

**Comment by nikivazou** [comment]
Yes! Can you make me owner too?

**Comment by ranjitjhala** [comment]
done (I think).


On Tue, Nov 17, 2015 at 10:01 AM, Niki Vazou <notifications@github.com>
wrote:

> Yes! Can you make me owner too?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquidhaskell/pull/513#issuecomment-157454113>
> .
>



-- 
Ranjit.

**Comment by nikivazou** [comment]
Yes, thanks! So when Travis likes it I will merge

**Pull request merged**
