### PR TITLE
reflect methods

### PR DESCRIPTION
**Pull request by nikivazou**
Another step closer to properly refining/reflecting classes

### CODE REVIEW

**Comment by ranjitjhala** [comment]
Can you get this up-to-date with the `import-reflects` branch? otherwise
there will be all sorts of merge-conflict hell.

**Comment by ranjitjhala** [comment]
As in: please do *not* merge this now...

**Comment by ranjitjhala** [comment]
Should this be merged?

**Comment by ranjitjhala** [comment]
@nikivazou my apologies, whats going on with this? can you fix the above conflicts and then we should merge in? or is it stale/dead? (if so close the PR?) Thanks!

**Comment by nikivazou** [comment]
Sorry, closing the PR.

**Pull request closed without merging**
