### PR TITLE
Make helpers for structDecreasing consistent.

### PR DESCRIPTION
**Pull request by rosekunkel**
Addresses @nomeata's concerns about the code style in my previous PR: https://github.com/ucsd-progsys/liquidhaskell/pull/1397#discussion_r251080249

### CODE REVIEW

**Comment by nomeata** [comment]
Heh, you actually resolved it the other way than I would have done (no need to abstract over `calls` when you always pass `calls` anyways). But this is getting philosophical…

**Comment by rosekunkel** [comment]
Well, I do call `raiseError` on both `calls` and `nonDec calls`. Granted, I don't think these error messages actually go anywhere...

**Comment by nomeata** [comment]
Good point.

**Review by nomeata — APPROVED** [review]

**Comment by ranjitjhala** [comment]
So this looks good right, shall I merge?

**Pull request merged**
