### PR TITLE
Update liquid-fixpoint after performance improvements to serialization

### PR DESCRIPTION
**Pull request by facundominguez**

### CODE REVIEW

**Comment by facundominguez** [comment]
There are many different failures here. 
* `store` doesn't build anymore in cabal_900
* `liquidhaskell` doesn't build anymore with cabal_810
* Various stack jobs fail on a test that takes to long to produce output
* stack_884_legacy_executable fails when downloading and extracting the docker image with ghc and stack.

I guess all of these will be fixed eventually. But I wanted to ask: is it worth running all of these jobs? For instance, does someone depend on `stack_865_legacy_executable` and `stack_884_legacy_executable` passing? What about appveyor?

**Comment by ranjitjhala** [comment]
Hmm, good point.

I thought Facundo updated `store`?

Also, yes, lets ditch 884 for sure!

Why is LH not building with cabal_810? That's rather unfortunate :-(

**Comment by facundominguez** [comment]
> Why is LH not building with cabal_810? That's rather unfortunate :-(

aeson released a new major version which changes the type used for keys.

**Comment by ranjitjhala** [comment]
Will a constraint to use the earlier version fix it?

**Comment by facundominguez** [comment]
I think there is a fix that works with both versions of aeson. I'm sending fixes here: https://github.com/ucsd-progsys/liquidhaskell/pull/1884

**Comment by facundominguez** [comment]
All green!

**Comment by ranjitjhala** [comment]
Thank you!!!

**Pull request merged**
