### PR TITLE
Varosi appveyor

### PR DESCRIPTION
**Pull request by ranjitjhala**
A new PR applying @varosi 's appveyor changes to the latest `develop`.

### CODE REVIEW

**Comment by ranjitjhala** [comment]
Hi @varosi -- looks like rebasing against the latest `develop` helps with circle. However, the appveyor builds are failing for two reasons:

1. the long file names?
2. somehow `HsColour` is not getting built due to some tab/spaces issue?


For 2 is it possible to disable that warning in the appveyor script?
~For 1 we could potentially split those giant "log" files into some separate repo? Would that help?~

~EDIT: actually looks like your renaming of the files was not applied in the PR. Hmm. Maybe I can just do it manually...~

Actually looks like it _was_ applied in the PR but somehow the appveyor build is still trying to checkout the files:

```
error: unable to create file tests/logs/regrtest_results_goto_Fri_Sep_21_17:19:54_2012: Invalid argument
error: unable to create file tests/logs/regrtest_results_goto_Mon_Feb__4_08:25:21_2013: Invalid argument
error: unable to create file tests/logs/regrtest_results_goto_Mon_Oct_22_15:45:04_2012: Invalid argument
error: unable to create file tests/logs/regrtest_results_goto_Mon_Oct_22_20:52:56_2012: Invalid argument
error: unable to create file tests/logs/regrtest_results_goto_Sat_Feb_23_18:38:19_2013: Invalid argument
error: unable to create file tests/logs/regrtest_results_goto_Sun_Jan_13_17:11:09_2013: Invalid argument
error: unable to create file tests/logs/regrtest_results_goto_Sun_Jul_13_22:12:12_2014_post_errormsg_parseparens: Invalid argument
error: unable to create file tests/logs/regrtest_results_goto_Sun_Oct_28_17:24:34_2012: Invalid argument
error: unable to create file tests/logs/regrtest_results_goto_Wed_Nov_20_15:28:50_2013-master: Invalid argument
error: unable to create file tests/logs/regrtest_results_nikiL_Fri_Mar_29_12:56:37_2013: Invalid argument
error: unable to create file tests/logs/regrtest_results_ubuntu_Fri_Jul_29_17:38:55_2011: Invalid argument
error: unable to create file tests/logs/regrtest_results_ubuntu_Mon_Dec__5_03:32:39_2011: Invalid argument
error: unable to create file tests/logs/regrtest_results_ubuntu_Sun_Sep_11_15:52:57_2011: Invalid argument
error: unable to create file tests/logs/regrtest_results_ubuntu_Sun_Sep_11_19:38:55_2011: Invalid argument
error: unable to create file tests/logs/regrtest_results_ubuntu_Sun_Sep_11_20:12:06_2011: Invalid argument
error: unable to create file tests/logs/regrtest_results_ubuntu_Thu_Dec_22_02:51:46_2011: Invalid argument
error: unable to create file tests/logs/regrtest_results_ubuntu_Tue_Jul_19_10:07:18_2011: Invalid argument
error: unable to create file tests/logs/regrtest_results_ubuntu_Wed_Dec_21_03:11:45_2011: Invalid argument
error: unable to create file tests/logs/regrtest_results_ubuntu_Wed_Dec_21_03:14:29_2011: Invalid argument
error: unable to create file tests/logs/regrtest_results_ubuntu_Wed_Dec_21_16:45:26_2011: Invalid argument
error: unable to create file tests/logs/regrtest_results_ubuntu_Wed_Dec_21_18:09:31_2011: Invalid argument
error: unable to create file tests/logs/regrtest_results_ubuntu_Wed_Dec_21_18:42:19_2011: Invalid argument
error: unable to create file tests/logs/regrtest_results_ubuntu_Wed_Dec_21_19:13:26_2011: Invalid argument
error: unable to create file tests/logs/regrtest_results_ubuntu_Wed_Dec_21_19:14:10_2011: Invalid argument
error: unable to create file tests/logs/regrtest_results_ubuntu_Wed_Sep__7_14:45:19_2011: Invalid argument
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
```

Any idea why?





Thanks!

**Comment by varosi** [comment]
Great about CircleCI! Problems with "Invalid agrument" are because of colons (":") in file names. In my branch (commit a992e59) I have renamed them to not have colons. It's strange that they are still present.

**Comment by varosi** [comment]
It's interesting that problem in hscolor is in it, not in liquidhaskell:

> C:\tmp\stack2544\hscolour-1.24.4\Language\Haskell\HsColour.hs:37:19: warning: [-Wtabs]
> 280        Tab character found here, and in two further locations.
> 281        Please use spaces instead.
> 282       |
> 283    37 |          -> String      -- ^ Title for output.
> 284       |                   ^^^^^^
> 285    ignoring (possibly broken) abi-depends field for packages
> 286

Something in the new LTS I think. We could try with some other version of it.

**Comment by ranjitjhala** [comment]
I disabled the `tabs` warning to make progress, but its getting stuck on something else, c.f.

https://ci.appveyor.com/project/ranjitjhala/liquidhaskell/builds/19440719

Do you know if it is possible to "log onto" the VM to inspect the log to see what the problem is?

**Comment by varosi** [comment]
I tried this: https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
It works well, but only from Windows machine doing remote desktop. 
You could cherry pick latest commit (33fe462ed5446e805f78e09ff4a44b3302c9b642) on my branch to enable RDP. 
One problem is that the VM is live only 60min. On my tests it is even less.

**Comment by varosi** [comment]
It's strange... your branch is building fine on my Windows machine. May be it's something with the VM. Could you restart the build?

**Comment by ranjitjhala** [comment]
Hmm... yes so there must be something odd going on in the appveyor vm?

**Comment by varosi** [comment]
@ranjitjhala, could you restart the CI? or push something to your branch so it try to rebuild? I don't have rights to push to that branch on your repo.

**Comment by varosi** [comment]
https://github.com/haskell/cabal/issues/5465

**Comment by varosi** [comment]
I have reproduced the error at my AppVeyor instance, so I'll try to fight it by myself - https://ci.appveyor.com/project/varosi/liquidhaskell/builds/19737975

**Comment by varosi** [comment]
I hit a bad error on AppVeyor using GHC 8.4 - https://github.com/commercialhaskell/stack/issues/4441 This problem is fixed in GHC 8.6. liquid-fixpoint module [is building with 8.6 just fine](https://ci.appveyor.com/project/varosi/liquidhaskell/builds/21047329). But building liquidhaskell itself rises lot of errors which are not trivial for me to fix without deep knowledge on LiquidHaskell. 

@ranjitjhala, do you have plans to make it build with 8.6?

**Comment by ranjitjhala** [comment]
Sure is 8.6 pretty stable now? Would be  good to upgrade.

**Comment by nikivazou** [comment]
Yes! 8.6 is the stable current release!

**Comment by varosi** [comment]
It's stable as @nikivazou said, all tests on all libraries in current Stackage nightly are passing on three OSes. And [it's close to release of LTS](https://www.stackage.org/blog/2018/11/upcoming-lts-13-ghc-8-6-2). As I know they don't do additional tests except those that are made on nightly bases automatically. [GHC compiler is updated twice after the official release](https://www.haskell.org/ghc/download_ghc_8_6_3.html) and soon we'll have it in LTS 13.

**Comment by varosi** [comment]
Happy LTS! Now with GHC 8.6.3
https://www.stackage.org/lts-13.0

**Comment by ranjitjhala** [comment]
Hi @varosi -- so if/when we move to GHC 8.6.3 then this should work? Ranjit.

**Comment by varosi** [comment]
Yes, I have tried to build fixpoint on AppVeyor with latest GHC 8.6. There
is a fix for that exact problem.
На сб, 29.12.2018 г., 18:40 ч. Ranjit Jhala <notifications@github.com>
написа:

> Hi @varosi -- so if/when we move to GHC 8.6.3 then this should work?
> Ranjit.
>
>

**Comment by varosi** [comment]
In 8.6 there are other Windows fixes as well - for example problems with
long paths are fixed there.
На сб, 29.12.2018 г., 23:57 ч. Vassil Ognyanov Keremidchiev <
varosi@gmail.com> написа:

> Yes, I have tried to build fixpoint on AppVeyor with latest GHC 8.6. There
> is a fix for that exact problem.
> На сб, 29.12.2018 г., 18:40 ч. Ranjit Jhala <notifications@github.com>
> написа:
>
>> Hi @varosi -- so if/when we move to GHC 8.6.3 then this should work?
>> Ranjit.
>>
>>

**Comment by nikivazou** [comment]
So, hopefully windows build is fixed with our upgrade!

**Comment by ranjitjhala** [comment]
What is the cause of this sunny optimism :) ?

**Comment by nikivazou** [comment]
In the comments @varosi said there is a fix in ghc-8.6

**Comment by varosi** [comment]
Yes, I have tested with GHC-8.6 before. 
So now LiquidHaskell use GHC-8.6! Yay! I'll test it

**Comment by ranjitjhala** [comment]
Thanks!!

**Comment by varosi** [comment]
https://github.com/ucsd-progsys/liquidhaskell/pull/1442

**Pull request closed without merging**
