### PR TITLE
Fix for #1657: check bounds on zero argument, bounded functions

### PR DESCRIPTION
**Pull request by nikivazou**
The problem is that in the new tests the bounded function has zero arguments. 
When we check bounds for functions with arguments, this code is used: https://github.com/ucsd-progsys/liquidhaskell/blob/develop/src/Language/Haskell/Liquid/Constraint/Generate.hs#L849 which adds this constraints by https://github.com/ucsd-progsys/liquidhaskell/blob/develop/src/Language/Haskell/Liquid/Constraint/Generate.hs#L1135 

When the bounded function has no arguments, the bounds are handled by this: https://github.com/ucsd-progsys/liquidhaskell/blob/develop/src/Language/Haskell/Liquid/Constraint/Generate.hs#L684
where `addPost` just dropped the bounds (encoded as `RRTy e r OCons t`). 

Two `STMonad` tests are now failing, thus moved them in `todo`.

### CODE REVIEW

**Comment by ranjitjhala** [comment]
Thanks @nikivazou !!!

Looks like the actual edit was a single line in `addPost` right?

1. Any idea why the two (old) tests are failing? (I'm guessing both use `fresh` which is another example of a "zero-argument" function?)

2. Also, does the modified version of the `pleaseFail` tests where the precondition is added to `pleaseFail` succeed?

**Comment by nikivazou** [comment]
> Thanks @nikivazou !!!
> 
> Looks like the actual edit was a single line in `addPost` right?

Yes! 

> 
> 1. Any idea why the two (old) tests are failing? (I'm guessing both use `fresh` which is another example of a "zero-argument" function?)

It is `fresh` indeed.

> 2. Also, does the modified version of the `pleaseFail` tests where the precondition is added to `pleaseFail` succeed?

I don't understand this question.

**Comment by ranjitjhala** [comment]
I mean that in e.g. `T1657.hs` if we instead wrote the signature

```haskell
{-@ shouldPass :: I<{\z -> z > 0}> @-}
shouldPass :: I
shouldPass = getI 
```

then does it verify? (Because if not, it means we're still not handling the 0-arg terms properly ...)

**Comment by nikivazou** [comment]
> ```haskell
> {-@ shouldPass :: I<{\z -> z > 0}> @-}
> shouldPass :: I
> shouldPass = getI 
> ```

No :( 
But it does if you add an extract `()` argument to `getI`. 
So, I guess something is still off and need to look more...

**Comment by ranjitjhala** [comment]
Interesting... I bet the “fresh” tests also have the same problem.

**Comment by ranjitjhala** [comment]
Thanks @nikivazou !!!

**Pull request merged**
