### PR TITLE
get quals from all used vars: fix for #1132

### PR DESCRIPTION
**Pull request by nikivazou**

### CODE REVIEW

**Comment by ranjitjhala** [comment]
Thanks @nikivazou!

**Comment by gridaphobe** [comment]
Be VERY careful with this. I tried enabling this same scraping from imported variables a while ago and it had disastrous performance consequences. I never fully tracked it down, but suspect it's due to some highly polymorphic qualifiers somewhere in the include files.

I think I scraped **all** imported variables rather than just the **used** variables though...

**Comment by ranjitjhala** [comment]
Ah yes ... that was still tucked into an option IIRC?

**Comment by gridaphobe** [comment]
Looks so :)

https://github.com/ucsd-progsys/liquidhaskell/blob/develop/src/Language/Haskell/Liquid/UX/CmdLine.hs#L263-L276

**Pull request merged**
