### PR TITLE
allow type class constraints in GADT definitions

### PR DESCRIPTION
**Pull request by nikivazou**

### CODE REVIEW

**Comment by bolt12** [comment]
Will this, by any chance, tackle #1633 ?

**Comment by nikivazou** [comment]
@bolt12, sure! Since I am locked down to GADTs I will look at #1633. 
The goal is still to verify the below?
```
import Data.Void

data Relation a b where
  Empty :: Relation Void Void
  One :: Int -> Relation () ()
  Join :: Relation c b -> Relation d b -> Relation (Either c d) b
  Fork :: Relation a c -> Relation a d -> Relation a (Either c d)

-- Here I use a type 'Natural 0 1' but I wanted to try and refine the GADT.
{-@
data Relation a b where
  Empty :: Relation Void Void
  | One :: {v:Int | v = 0 || v = 1} -> Relation () ()
  | Join :: Relation c b -> Relation d b -> Relation (Either c d) b
  | Fork :: Relation a c -> Relation a d -> Relation a (Either c d)
@-}

-- (Eq, Num, Ord, etc.. instances ...)

comp :: Relation b c -> Relation a b -> Relation a c
comp Empty Empty           = Empty
comp (One a) (One b)       = One (a * b)
comp (Join a b) (Fork c d) = comp a c + comp b d         -- Divide-and-conquer law
comp (Fork a b) c          = Fork (comp a c) (comp b c) -- Fork fusion law
comp c (Join a b)          = Join (comp c a) (comp c b)  -- Join fusion law
```

**Comment by bolt12** [comment]
Yes! I also had problems using the `reflect` tag on a function that consumes a GADT.

> I tried to add reflect to the signature of `comp` and I got the following error:

```haskell
**** DONE:  A-Normalization ****************************************************


**** DONE:  Extracted Core using GHC *******************************************


**** DONE:  Transformed Core ***************************************************

liquid: safeBkArrow on RAllTforall c##X21b d##X21e .
(~#<[]> (TYPE 'GHC.Types.LiftedRep) (TYPE 'GHC.Types.LiftedRep) c##a2Nv (Data.Either.Either c##X21b d##X21e)) =>
lq_tmp$x##1728:(Relation.Relation c##X21b b##a2Nt) -> lq_tmp$x##1729:(Relation.Relation d##X21e b##a2Nt) -> (Relation.Relation c##a2Nv b##a2Nt)
CallStack (from HasCallStack):
error, called at src/Language/Haskell/Liquid/Types/Types.hs:1327:31 in liquidhaskell-0.8.6.0-8uYkE0Yspwt3GvEhvWjkte```

**Comment by nikivazou** [comment]
Cool! 
I also run into your error, so will eventually address that too. 
(But, I am still trying to understand when it is "OK" to reflect these fancy definitions...)

**Comment by bolt12** [comment]
@nikivazou Thanks! If there's any way I can help even the slightest please tell me. I'm not familiar with the internal but I can find some tyme to look into it :)

**Pull request merged**
