### PR TITLE
Remove colouring of output, because it makes problems in latest Stack 2.1

### PR DESCRIPTION
**Pull request by varosi**

### CODE REVIEW

**Comment by nikivazou** [comment]
Thanks @varosi-chaosgroup, the appveyor is still failing :(

**Comment by varosi-chaosgroup** [comment]
>       Hole00.hs:                      FAIL (0.24s)
>         tests\\test.hs:442:
>         Wrong exit code
>         expected: ExitSuccess
>          but got: ExitFailure 1
>       HiddenMethod00.hs:              OK (1.82s)
>       Class00.hs:                     OK (1.81s)

This test fail which is not connected with colouring output.

**Comment by ranjitjhala** [comment]
Yes it works fine on the Linux and Mac which is puzzling!

Can you tell us how we can get the logs? Ie can we say into the machine
where the tests are run etc?

The other option would be to disable this test on windows?

**Comment by varosi** [comment]
Seems that it's working now, so I'm closing this pull request.

**Pull request closed without merging**
