### PR TITLE
QuasiQuoters

### PR DESCRIPTION
**Pull request by spinda**
This adds an `lq` quasiquoter which outputs both annotations that LH can extract specifications from and regular Haskell type signatures/type synonyms.

### CODE REVIEW

**Comment by ranjitjhala** [comment]
Nice! Is this ready to be merged?

**Comment by spinda** [comment]
Yep!

**Comment by tolysz** [comment]
Any chance of updating this commit(resolving conflicts) and merging into develop?

**Comment by ranjitjhala** [comment]
Oops! Thanks for the reminder! @spinda looks like there are conflicts! Any chance you can take a look at this and merge? Perhaps after finals week :) ?

**Comment by spinda** [comment]
Ah, I thought this would have been merged already. Will get it up to date and merged when I can.

**Comment by spinda** [comment]
Ready to merge. Should I hit the green button now?

**Comment by ranjitjhala** [comment]
Yes please!

**Comment by ranjitjhala** [comment]
btw, @spinda -- since this is a cool new feature, can you add something to
the README about it? At the very least, links to the files in `tests/pos`
that demonstrate how it
is used?

Thanks!

**Comment by spinda** [comment]
Done and done!

**Comment by ranjitjhala** [comment]
Did you _just_ do this?

**Comment by ranjitjhala** [comment]
thanks!

**Pull request merged**
