### PR TITLE
ackermann

### PR DESCRIPTION
**Pull request by nikivazou**
More edits to enable pretty proofs of functional properties

### CODE REVIEW

**Comment by gridaphobe** [comment]
I don't think we need a `--scrape-assumed` flag, it should just be done always.

**Comment by nikivazou** [comment]
I deactivated the always: we just scrape the quals from assumed signatures when the flag is on. You think it is a bad idea?

**Comment by gridaphobe** [comment]
No, I think we should always be scraping quals from assumed **and** asserted signatures. (Unless there are examples where it kills performance)

**Comment by nikivazou** [comment]
I am auto-generating some assumed sigs and I really want to ignore the qualifiers from these auto generated signatures. 
The ignore-assumed was the easy solution. I will mark these signs as internals instead and ignore the internal sigs quals

**Comment by gridaphobe** [comment]
Ah, I see. Ignoring generated sigs seems fine, but we definitely shouldn't ignore user-written sigs :)

**Pull request merged**
