### PR TITLE
Cutsolver

### PR DESCRIPTION
**Pull request by ranjitjhala**
More major surgery with the parser etc. (now kvars look like `$k_0` etc.) see `tests/{pos,neg}/*.fq`

see: https://github.com/ucsd-progsys/liquid-fixpoint/pull/65

### CODE REVIEW

**Comment by ranjitjhala** [comment]
Can someone (e.g. @spinda or @gridaphobe) please restart TrAVIS on this? I think its using the stale liquid-fixpoint

**Comment by gridaphobe** [comment]
@ranjitjhala I restarted travis after merging the fixpoint branch, but there are still a ton of failing tests :/

**Comment by ranjitjhala** [comment]
Could it be using a stale FP binary? (There are no failing tests for me locally except the usual suspect "while")

**Comment by nikivazou** [comment]
WhileM.hs should not fail *locally*, as least it does not fail for me on master.

**Comment by gridaphobe** [comment]
@ranjitjhala travis is rebuilding FP from scratch, but there appears to be a merge conflict that github is not detecting..

https://travis-ci.org/ucsd-progsys/liquidhaskell/jobs/61715682#L716-L717

**Pull request merged**
