### PR TITLE
Parser rewrite, adding layout-sensitive parsing.

### PR DESCRIPTION
**Pull request by kosmikus**
[ matches PR https://github.com/ucsd-progsys/liquid-fixpoint/pull/444 ]

 ** @kosmikus suggests to merge this _after_ the new 8.10 release**

This builds on #1703 and contains the actual changes to the parser.
There is still a lot more to do. I have created a project
(https://github.com/ucsd-progsys/liquidhaskell/projects/4)
that shows known parser bugs and how they are affected by
this PR.

This should probably only be merged after the plugin release ...

The most important changes are:

- Rewrite to use megaparsec rather than parsec, according
  to similar changes applied to liquid-fixpoint.

- Add layout-sensitive parsing. This makes the parser more
  strict in some situations. In particular, multiple lines
  that belong to a single LH "command" now must be indented
  in such a way that subsequent lines start at a later column
  than the initial line. The benefit is that multiple commands
  can be included in a single spec comment, and that line breaks
  work as expected in all situations, i.e. anything can be
  split across multiple lines. Previously, there was a hack that
  disallows line-breaks in some situations to ensure that
  some mult-line directives such as e.g. (instance) measures
  are parsed correctly. Also, explicit block parsing via
  braces and semicolons is now possible, so layout is
  optional.

- Error message reporting range calculations should be
  somewhat improved, although more remains to be done in
  this area.

- An error in datatype parsing is fixed which meant that
  datatypes without record fields are often incorrectly
  parsed (#871).

- Other open issues fixed by these changes are
  #707, #788, #873, #892, #924, #1012, #1481 and #1531.

- The test system is improved so that negative/positive
  tests do not purely look for the exit code, but check that
  there was not simply a parse error. This should improve
  the value of negative tests.

- The test system is improved so that we can test spec-file
  parsing individually. This is used to demonstrate that
  the situations in which previously redundant parentheses
  needed to be added in order to make the parser recognise
  the end of a declaration correctly are gone.

- Add test cases for #338 and #884, which I think have
  been working already in the current version, independently
  of the parser changes.

- Add some more comments.

### CODE REVIEW

**Comment by kosmikus** [comment]
This has now been updated / rebased on latest develop. Depends on ucsd-progsys/liquid-fixpoint#444.

**Comment by kosmikus** [comment]
My current analysis is that the `cabal_810` CI failure is a dependency glitch that is a real problem, but one that in principle exists independently of this PR.

**Comment by nikivazou** [comment]
Is it difficult to add the missing instance? 
The gradual functionality (and the relevant code) is not used tbh. So, you can add a dummy instance and soon I can clean all this unused/gradual code.

**Comment by kosmikus** [comment]
@nikivazou There is no missing instance, really. It's a dependency problem that can occur due to unfortunately imprecise dependency bounds in various places. The stack builds which have locked dependencies are all ok. Alfredo and I will fix this soon.

**Review by ranjitjhala — APPROVED** [review]

**Pull request merged**
