### PR TITLE
Add a stricter check in the type specifications

### PR DESCRIPTION
**Pull request by nikivazou**
checking with Travis

### CODE REVIEW

**Comment by ranjitjhala** [comment]
@nikivazou is this for issue #468 or something else? (And either way should we wait or merge?)

**Comment by nikivazou** [comment]
It is something else: function binders do not go into fixpoint environment, but when we check type signatures we do insert function binders in the check-environment. So a signature

```
foo :: f:(a -> b) -> x:a -> {v:b | v == f x }
```

will be treated as well-formed. Which is wrong because pruning of unsorted refinements will discard the unsorted `v == f x`, since `f` will be out of scope. And this can lead to unsoundness.

**Comment by ranjitjhala** [comment]
Eeks. So merge?

**Comment by nikivazou** [comment]
Yes! I was waiting for Travis

**Pull request merged**
