### PR TITLE
add MiniPosix test

### PR DESCRIPTION
**Pull request by abakst**
At the very bottom of this file is 'createTest,' which depends on an implementation of select/update in fixpoint.

### CODE REVIEW

**Comment by ranjitjhala** [comment]
What is `C` in this definition?

https://github.com/ucsd-progsys/liquidhaskell/pull/315/files#diff-7e9f1889873e11772fae9a80cca1e43eR26



On Tue, Jan 20, 2015 at 6:45 PM, Alexander Bakst <notifications@github.com>
wrote:

> At the very bottom of this file is 'createTest,' which depends on an
> implementation of select/update in fixpoint.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/ucsd-progsys/liquidhaskell/pull/315
> Commit Summary
>
>    - add MiniPosix test
>
> File Changes
>
>    - *A* tests/icfp15/MiniPosix.hs
>    <https://github.com/ucsd-progsys/liquidhaskell/pull/315/files#diff-0>
>    (96)
>
> Patch Links:
>
>    - https://github.com/ucsd-progsys/liquidhaskell/pull/315.patch
>    - https://github.com/ucsd-progsys/liquidhaskell/pull/315.diff
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquidhaskell/pull/315>.
>



-- 
Ranjit.

**Comment by abakst** [comment]
Just above it...C is the data constructor for a capability

**Comment by nikivazou** [comment]
@abakst, do you think we can give the implementation of the functions (instead of `undefined`) and still typecheck them?

**Comment by abakst** [comment]
It's possible. These functions are from the System.Posix library, which is probably just a wrapper around some FFI calls. If the System.Posix library isn't doing anything fancy, then perhaps. We'd still have to write similar specs for the FFI calls. Is there an advantage doing verifying those implementations?

**Pull request merged**
