### PR TITLE
remove unresonable check

### PR DESCRIPTION
**Pull request by nikivazou**

### CODE REVIEW

**Comment by ranjitjhala** [comment]
@nikivazou please don't remove this check; as you can see from the failed test, it is actually quite a reasonable one!

**Comment by ranjitjhala** [comment]
maybe the real q is: why is this check failing on @jbrown215 's code?

**Comment by nikivazou** [comment]
Yes! This is why I removed it. 
The check is needed but it is too restrictive, e.g., it rejects @jbrown215 's well sorted example. 

I do not think I can properly relax the check any time soon :(

**Comment by ranjitjhala** [comment]
Ok fine, let’s comment out that failing test, and
we can come back to this when I torch and
rewrite the absref code ... 😀

**Pull request merged**
