### PR TITLE
Enabled -Werror in cabal file, fixed warnings

### PR DESCRIPTION
**Pull request by christetreault**
I've enabled `-Werror` unconditionally in the `liquidhaskell.cabal` file. I fixed the warnings that then became build failures. The following commented blocks of code could use the attention (at some point) of their owners:

Bare/Axiom.hs:
- https://github.com/ucsd-progsys/liquidhaskell/blob/9dd983ce0a9a95ad9a0929a8a09ad04164bc23d1/src/Language/Haskell/Liquid/Bare/Axiom.hs#L75-L80
- https://github.com/ucsd-progsys/liquidhaskell/blob/9dd983ce0a9a95ad9a0929a8a09ad04164bc23d1/src/Language/Haskell/Liquid/Bare/Axiom.hs#L90-L101
- https://github.com/ucsd-progsys/liquidhaskell/blob/9dd983ce0a9a95ad9a0929a8a09ad04164bc23d1/src/Language/Haskell/Liquid/Bare/Axiom.hs#L119-L122
- https://github.com/ucsd-progsys/liquidhaskell/blob/9dd983ce0a9a95ad9a0929a8a09ad04164bc23d1/src/Language/Haskell/Liquid/Bare/Axiom.hs#L125-L126
- https://github.com/ucsd-progsys/liquidhaskell/blob/9dd983ce0a9a95ad9a0929a8a09ad04164bc23d1/src/Language/Haskell/Liquid/Bare/Axiom.hs#L129-L134

Constraint/ProofToCore.hs:
- https://github.com/ucsd-progsys/liquidhaskell/blob/9dd983ce0a9a95ad9a0929a8a09ad04164bc23d1/src/Language/Haskell/Liquid/Constraint/ProofToCore.hs#L79-L83

Constraint/Qualifier.hs:
- https://github.com/ucsd-progsys/liquidhaskell/blob/9dd983ce0a9a95ad9a0929a8a09ad04164bc23d1/src/Language/Haskell/Liquid/Constraint/Qualifier.hs#L113-L133
- https://github.com/ucsd-progsys/liquidhaskell/blob/9dd983ce0a9a95ad9a0929a8a09ad04164bc23d1/src/Language/Haskell/Liquid/Constraint/Qualifier.hs#L144-L150

UX/CmdLine.hs:
- https://github.com/ucsd-progsys/liquidhaskell/blob/9dd983ce0a9a95ad9a0929a8a09ad04164bc23d1/src/Language/Haskell/Liquid/UX/CmdLine.hs#L417-L419

UX/PrettyPrint.hs
- https://github.com/ucsd-progsys/liquidhaskell/blob/9dd983ce0a9a95ad9a0929a8a09ad04164bc23d1/src/Language/Haskell/Liquid/UX/PrettyPrint.hs#L324-L337

### CODE REVIEW

**Comment by gridaphobe** [comment]
I'll go ahead and repeat my objection to enabling `-Werror` unconditionally, though I'm clearly in the minority :-)

Making `-Werror` slows down the pace of development by forcing you to address minute issues -- like defined-but-not-used variables and import cleanliness -- before you can actually test your code. `-Werror` belongs in travis for certain, but not in local builds by default.

**Comment by ranjitjhala** [comment]
Was wondering what the objection was.

Don't really buy the "slowing the pace of development"
because if you have these on all the time, i.e. while
editing/writing code, then they're just immediately
pruned well before you even think of testing.

If its in travis, but not in the regular build,
it will *never* get fixed. These should be on
all the time, while editing even.

In short: everybody please just use hlint/hdevtools/ghc-mod equivalent!

**Comment by christetreault** [comment]
Maybe we can have a cabal flag that disables -Werror? We can develop with Werror disabled, then the main release build target (that travis presumably builds) can have it enabled?

**Comment by nikivazou** [comment]
I am definitely in favor of turning Warnings to Errors! @christetreault should I merge this?

**Comment by christetreault** [comment]
I say we merge it. It seems we have conflicts now though, let me resolve them first, then I assume I'm cleared to merge?

**Comment by christetreault** [comment]
After merging the updates to Axiom.hs locally, I'm getting a fun new error:

```
src/Language/Haskell/Liquid/Liquid.hs:102:20:
    No instance for (Language.Haskell.Liquid.Types.Result
                       (FixResult (Language.Fixpoint.Types.Constraints.WrappedC Cinfo)))
      arising from a use of ‘ferr’
    In the expression: ferr sol r
    In an equation for ‘res’: res = ferr sol r
    In the expression:
      do { finfo <- cgInfoFInfo info cgi tgt;
           Result r sol <- solve fx finfo;
           let names = checkedNames dc;
           let warns = logErrors cgi;
           .... }
```

Anybody know what this is about? Relevant line of code in Liquid.hs:

https://github.com/ucsd-progsys/liquidhaskell/blame/master/src/Language/Haskell/Liquid/Liquid.hs#L118

**Comment by ranjitjhala** [comment]
should we be merging this btw?

**Comment by christetreault** [comment]
All these changes are going to be rolled into the refactor-ref pull request that is hopefully coming today. Closing this one.

**Pull request closed without merging**
