### PR TITLE
fix for #2369

### PR DESCRIPTION
**Pull request by nikivazou**
Partial function type applications work again, by adding the multiplicity parameter to the fun type constructor.

### CODE REVIEW

**Comment by facundominguez** [comment]
The cabal file is enabling -XHaskell2010 which causes the test to fail. Changing the type annotation fixes it, but see if that interferes with what you are trying to test.

**Comment by nikivazou** [comment]
Well, the main edit fixed #2369 locally for me (without the `XHaskell2010`), so when circle approves we can merge? 
Maybe @gergoerdi can confirm that the original example passes?

**Comment by facundominguez** [comment]
I think we can merge.

I was a bit concerned that my type annotation would hide the bug, but I just checked that without your fix the reported error still shows up with my edits.

**Comment by gergoerdi** [comment]
> Maybe @gergoerdi can confirm that the original example passes?

Indeed I can confirm that the original modules that prompted me to report this now work with LH.

**Pull request merged**
