### PR TITLE
WIP update to latest liquid-fixpoint

### LINKED ISSUE #2288: PLE crashes when using Set theory symbols
The following code crashes silently with `Sorry, unexpected panic in liquid-fixpoint!` when either the `assert` is uncommented or the line starting with `===` in the `otherwise` branch is commented out.

```haskell
{-@ LIQUID "--reflection" @-}
{-@ LIQUID "--ple"        @-}

module Test where

import Prelude
import Data.Set as S
import Language.Haskell.Liquid.ProofCombinators

{-@ reflect assert @-}
{-@ assert :: b:{Bool | b} -> x:a -> {v:a | v == x && b} @-}
assert :: Bool -> a -> a
assert _ x = x

{-@ reflect cat @-}
cat :: [a] -> [a] -> [a]
cat [] ys = ys
cat (x : xs) ys = x : cat xs ys

{-@ lemma :: (Ord a, Eq a)
              => xs:[a] -> ys:[a]
              -> z:{a | S.member z (S.fromList xs) }
              -> { S.member z (S.fromList (cat xs ys)) }
              @-}
lemma :: (Ord a, Eq a) => [a] -> [a] -> a -> ()
lemma [] ys z = ()
lemma (x : xs) ys z
  | z == x =
    ---assert (S.member z (S.fromList (cat (x : xs) ys)))
              ()
  | otherwise =
    S.member z (S.fromList (cat (x : xs) ys))
    === S.member z (S.fromList (x : cat xs ys))
    ? lemma xs ys z
    *** QED
```

It is likely that the PLE code throws some unhandled error, which is perhaps triggered by the change in the interpretation of Set symbols in https://github.com/ucsd-progsys/liquid-fixpoint/pull/688

### PR DESCRIPTION
**Pull request by clayrat**
Fixes #2288 

Don't merge yet (before https://github.com/ucsd-progsys/liquid-fixpoint/pull/696), the LF submodule currently points to a branch of a fork.

This updates LF to the version with compacted sort coercions for Sets, which fixes crashes for PLE-heavy code resulting from missing coercions.

### CODE REVIEW

**Comment by clayrat** [comment]
filtered
bot
top

**Comment by ranjitjhala** [comment]
Odd to see the `Data.Map.Base` slowdown; it doesn't really use `Set` does it?

**Comment by clayrat** [comment]
@ranjitjhala I think everything after the first ~8 slowdowns is more or less statistical noise, and we should focus first on regaining performance on large benchmarks which do not use `Set`/`Map`. I've found out that disabling the coercions just on the `Elaborate` code path (while keeping them on `Checkable`) is enough to get the perf back, so the plan is currently to automatically decide whether the elaborator should perform the full coercion on the environment based on whether `Set`/`Map` sort symbols are used in it.

**Comment by clayrat** [comment]
After some investigating, I've discovered that the environment coercion on the `Elaborate` code path is the biggest offender in terms of performance and moved it earlier to the point of environment creation. I think the charts look much better now:

filtered
bot
top

**Comment by ranjitjhala** [comment]
Great, thank you!!!

- Ranjit.

**Comment by nikivazou** [comment]
Much better! Let's merge! 

BTW, did you add a test that could not run before (i.e., was creating a crash) and passes now? I believe the feature of this PR should close some issues related with sets and SMT crashing!

**Comment by clayrat** [comment]
> Much better! Let's merge!
> 
> BTW, did you add a test that could not run before (i.e., was creating a crash) and passes now? I believe the feature of this PR should close some issues related with sets and SMT crashing!

Oh yeah, that's a good point, the initial issue was one missing local coercion that I subsequently added to make some PLE-enabled code in dynamic-policies go through. I'll add a minimized form of that code as a new test.

**Comment by clayrat** [comment]
Added a new test and inserted an additional coercion in LF (see https://github.com/ucsd-progsys/liquid-fixpoint/pull/696#issuecomment-2225652088), here are the new performance charts:

filtered
bot
top

**Pull request merged**
