### PR TITLE
Fix error reporting for #T1498

### PR DESCRIPTION
**Pull request by nikivazou**
Re #1498.

- 0: 
```
class A a where
  f :: a -> Int

instance A Int where
  {-@ f :: _ -> {x : Int | 0 < x} @-}
  f n = n

{-@ x :: {x : Int | 0 < x} @-}
x :: Int
x = f ((-1) :: Int)
```
Reports 
```
 Invalid type specification for Main.f
 Use class or instance refinements instead.
```

- 1:
```
class A a where
  f :: a -> Int

instance A Int where
{-@
instance A Int where
  f :: _ -> {x : Int | 0 < x}
@-}
  f n = (-1)
```
Reports 
```
Error: Bad Data Specification

 7 |   f :: _ -> {x : Int | 0 < x}
            ^
 Cannot resolve type hole `_`. Use explicit type instead. for `f`
```

- 2: Similar to 1

### CODE REVIEW

**Comment by ranjitjhala** [comment]
Niki, can you add a link in the read me to some examples that use class and
instance refinements so that we can point Users those to those to see what
the syntax is? Thanks!

**Comment by nikivazou** [comment]
This is not good? https://github.com/ucsd-progsys/liquidhaskell#modules-with-code-type-classes

**Comment by ranjitjhala** [comment]
If that’s current then perfect! (I somehow thought the syntax had changed
but maybe that was for the laws?)

**Comment by nikivazou** [comment]
Yes, I did not change anything. 
Just adding some proper error messages when LH used to crash before.

**Pull request merged**
