### PR TITLE
New Z3 4.8.6 on Windows in develop branch

### PR DESCRIPTION
**Pull request by varosi**

### CODE REVIEW

**Comment by varosi** [comment]
It's working fine with tests on Windows.

**Comment by nikivazou** [comment]
Thanks a lot!

**Comment by ranjitjhala** [comment]
Did the CI build for develop just break?

**Comment by nikivazou** [comment]
It is broken because the cabal build goes out of memory (in develop too). I have a fix for that in a branch I am working on and will shortly create a PR.

**Pull request merged**
