### PR TITLE
Blow away stale sandbox

### PR DESCRIPTION
**Pull request by alanz**

### CODE REVIEW

**Comment by gridaphobe** [comment]
@alanz looks like the `~` in `~/cabal-sandbox` isn't being expanded correctly.

From the build log:
```
$ cabal sandbox --sandbox=~/cabal-sandbox init
Writing a default package environment file to
/home/ubuntu/liquidhaskell/cabal.sandbox.config
Creating a new sandbox at /home/ubuntu/liquidhaskell/~/cabal-sandbox
```

```
Creating dependency cache from the following paths:
...
  ✗ /home/ubuntu/cabal-sandbox
...
Creating source cache from the following paths:
  ✓ /home/ubuntu/liquidhaskell/.git
```

Thanks for all the work you're putting in to this!

**Comment by alanz** [comment]
ok, so the build works because it is a fresh sandbox.

**Comment by ranjitjhala** [comment]
yes, many MANY thanks -- we've been quite foxed by this business!!!

**Comment by gridaphobe** [comment]
Looks like circle is happy!

**Pull request merged**
