### PR TITLE
Build on stack lts-16.8

### LINKED ISSUE #1729: Please support Diff-0.4.x
Current release versions of `liquidhaskell` cannot be built in an LTS-16.x environment because the package does not support `Diff-0.4.x`. Would that be difficult to rectify?

### PR DESCRIPTION
**Pull request by ranjitjhala**
Fixes #1729

### CODE REVIEW

**Comment by peti** [comment]
Wouldn't you have to modify the Cabal file, too, to allow the build to use Diff-0.4.x?

**Comment by kosmikus** [comment]
Yes, agreed. The upper bound on `Diff` should be changed. It only works with `stack` because `stack.yaml` currently has `allow-newer` set.

**Comment by ranjitjhala** [comment]
Oops should have stuck with @DanBurton's #1746

**Comment by ranjitjhala** [comment]
Hi @peti -- can you let me know if this works for you? Thanks! Ranjit.

**Comment by peti** [comment]
I ran `cabal build --constraint="Diff >= 0.4"` with a recent git checkout and it compiled fine. Thank you very much.

**Pull request merged**
