### PR TITLE
bump Fixpoint, fixpoint API

### PR DESCRIPTION
**Pull request by atondwal**
AxiomEnv cleanup

### CODE REVIEW

**Comment by ranjitjhala** [comment]
Is this up-to-date with @nikivazou 's recent GHC8 PR?

**Comment by atondwal** [comment]
Ah, no, it isn't.

**Comment by ranjitjhala** [comment]
Can you make it so? (Should be easy, most of her stuff is in LH, while yours is in LF)?

**Comment by atondwal** [comment]
Yeah, I think so

On May 3, 2017 03:28, "Ranjit Jhala" <notifications@github.com> wrote:

Can you make it so? (Should be easy, most of her stuff is in LH, while
yours is in LF)?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ucsd-progsys/liquidhaskell/pull/1017#issuecomment-298874849>,
or mute the thread

**Pull request merged**
