### PR TITLE
Implement --ple-with-undecided-guards

### LINKED ISSUE #602: Disable expansion of reflected functions with unevaluated guards
When working on #500, my plan was to stop generating equations in PLE like
```Haskell
length xs = if null xs then 0 else 1 + length (tail xs)
```
Instead, we would only produce `length xs = 0` or `length xs = 1 + length (tail xs)` when `xs` can be proven to be either empty or non-empty.

This would work most of the time, and many proofs are easy to adapt by splitting them in cases, but a couple of brainy modules in [liquidmeta](https://github.com/michaelborkowski/liquidmeta/) depended on the undecided guards to show up in equations anyway, and I ran out of steam to figure out fixing those.

PLE today generates `length xs = if null xs then 0 else 1 + length (tail xs)` at the end of the algorithm, for every application of `length` in candidate expressions whose guards couldn't be decided. Because most of the time these equations aren't needed, I'd like to propose putting them behind a flag. So the `--ple` behavior would omit these equations with undecided guards by default, but if the user wants them, they can be generated with a flag `--ple-with-undecided-guards`.

The purpose of this is to make PLE effect on the SMT solver more predictable, and to clean the set of generated equations. I don't anticipate any performance improvements because of this.

How does that sound?

### PR DESCRIPTION
**Pull request by facundominguez**
Closes ucsd-progsys/liquid-fixpoint#602

Companion PR of ucsd-progsys/liquid-fixpoint#603

### CODE REVIEW

**Comment by facundominguez** [comment]
It is worth paying some attention to the modifications in the tests.

The functions `NegNormalForm.not` and `WhyLH.max` both need to be unfolded to save the user quite some trouble. In the case of `NegNormalForm.not` the SMT solver can use some reasoning on booleans, otherwise the user has to write lemmas to prove that `not` is an inverse of itself, and the de Morgan laws.

In these cases, I'm using a function `pleUnfold` that behaves like `id`, but it additionally fools the PLE algorithm into expanding the equation in which it is used. If we are to adopt this function, it should be moved somewhere like to `liquid-prelude` I guess (?).

Alternatively, we could try to come up with some heuristic to unfold functions with undecided guards. Unfolding non(mutually)-recursive functions by default could work in all the cases I've seen. But PLE doesn't have readily available a graph analysis of function definitions.

**Comment by ranjitjhala** [comment]
Hmm interesting - I don’t quite follow this clever trick you are using with
pleUnfold …

**Comment by facundominguez** [comment]
PLE won't unfold

```Haskell
not b = if b then False else True
```

if nothing is known about `b`. The problem for PLE is that `not` starts with an if-statement whose condition `b` is undecided. Therefore, I can give it such a decided condition by rewriting `not` to

```Haskell
not b = if True then if b then False else True else True
```

This almost works, but some simplification in LH is turning that to the original definition. Therefore, I make it a bit harder to simplify by hiding the `True` condition in an auxiliary definition.

```Haskell
not b = if bTrue then if b then False else True else True
  where
    bTrue = True
```

Now PLE unfolds `not` but the definition is ugly to read for the user. So instead, I factor out the surrounding code to `pleUnfold`, obtaining

```Haskell
not b = pleUnfold (if b then False else True)

-- | Forces the PLE algorithm to unfold the definitions that use @pleUnfold@
{-@ reflect pleUnfold @-}
pleUnfold :: a -> a
pleUnfold a = if bTrue then a else a
 where
   bTrue = True
```

**Comment by ranjitjhala** [comment]
aha, got it, thanks :-)

**Comment by ranjitjhala** [comment]
Would be great to have a more permanent note about this, wherever we
explain the `--ple-with-undecided-guards` flag.

**Comment by ranjitjhala** [comment]
By, which I mean -- maybe we can just copy paste your above explanations
into the relevant place?

**Comment by facundominguez** [comment]
> By, which I mean -- maybe we can just copy paste your above explanations into the relevant place?

I think it is good idea to document the existence of `pleUnfold`. I wasn't sure if it was good enough to keep, but in that case, we can make it less tricky by just hardcoding it in PLE. Whenever PLE finds a body that starts with an application of `Language.Haskell.Liquid.ProofCombinators.pleUnfold`, it proceeds with the unfolding.

The heuristics to decide when to unfold equations will be adjusted over time, I presume, and keeping `pleUnfold` as it is now would be a bit fragile.

**Comment by facundominguez** [comment]
I documented `pleUnfold`, and put it in `Language.Haskell.Liquid.ProofCombinators`, and hardcoded it in PLE.

**Comment by facundominguez** [comment]
I rebased to update LF with another fix. On my side this looks good to merge.

**Comment by facundominguez** [comment]
@ranjitjhala, is this good to merge?

**Comment by ranjitjhala** [comment]
oy I thought we had merged it -- lets do so! thanks @facundominguez !!!

**Comment by ranjitjhala** [comment]
(and any matching PR in fixpoint too of course)

**Comment by ranjitjhala** [comment]
oops looks like the `STLC.hs` test is broken in the `cabal_900` build -- any idea why?

**Comment by facundominguez** [comment]
CI is passing in the `develop` branch. Do you have a link to the failing job?

**Comment by ranjitjhala** [comment]
https://app.circleci.com/pipelines/github/ucsd-progsys/liquidhaskell/1353/workflows/69ecdfe8-de27-48ec-b5cc-63e79bc198f6/jobs/7954

**Comment by facundominguez** [comment]
Unfortunately, rerunning the job doesn't cause it to fail. So we have a new little project in our hands: track and fix the sources of non-determinism in LH :)

**Comment by facundominguez** [comment]
I created https://github.com/ucsd-progsys/liquidhaskell/issues/2020 which could help investigating these flaky failures.

**Comment by michaelborkowski** [comment]
Hi Facundo, how would I try to use `pleUnfold` with a function defined with multiple equations instead of an explicit `if .. then ... else`? For instance

```
{-@ reflect isValue @-} -- meaning: is a syntactic value 
isValue :: Expr -> Bool
isValue (Prim _)        = True
isValue (FV _)          = True 
isValue (BV _)          = True 
isValue (Lambda   e)    = True 
isValue (LambdaT   k e) = True
isValue _               = False
```

**Comment by facundominguez** [comment]
Hello! How about
```
{-@ reflect isValue @-}
isValue :: Expr -> Bool
isValue e0 = pleUnfold (case e0 of
  (Prim _)        -> True
  (FV _)          -> True 
  (BV _)          -> True 
  (Lambda   e)    -> True 
  (LambdaT   k e) -> True
  _               -> False)
```
?

**Comment by ranjitjhala** [comment]
Awesome, lets merge!

**Pull request merged**
