### PR TITLE
Revamp Docs

### PR DESCRIPTION
**Pull request by yanhasu**
As discussed in #1852, the `docs` site could do with an update.

TODO:
- [x] Upgrade nav & theme
- [x] Update existing content from `docs`
- [x] Port non-blogpost content from `blog` to `docs`
- [x] Tidy up

### CODE REVIEW

**Comment by yanhasu** [comment]
The new docs site can be previewed at https://yanhasu.github.io/liquidhaskell/

Feedback very welcome! There are probably many details that could be improved.

**Comment by yanhasu** [comment]
Bonus feature: the blogposts themselves are now ported to the docs!

(currently the date/author/etc. metadata is invisible, and some of the code listings are formatted bizzarely, but batch-processing should fix that...)

@ranjitjhala are there any details of your blog-posting workflow you would like to have supported/automated by mkDocs?

**Comment by ranjitjhala** [comment]
The main thing was that the posts were LHS files that were first run through LH to generate the markdown - I think that’s fine to still leave manual. Maybe the tricky part is pulling in the css needed to render the type tool tips?

**Comment by yanhasu** [comment]
OK, I'll look into generating/scraping the tooltips.

Are these LH-generated tooltips the main reason for not using [literate haskell markdown](https://gitlab.haskell.org/ghc/ghc/-/wikis/literate-markdown) directly?

**Comment by ranjitjhala** [comment]
Yes, so instead the LH converts code blocks to html with tooltip
annotations and then pandoc converts the rest to html. If there is a way to

1. Tell mkDocs to ignore html
2. Include the relevant css files

That should do the trick!

**Comment by yanhasu** [comment]
OK, the blog is ported!

Most of the features of the old blog are included, with the notable exception of the Disqus comment system, since (1) it keep trying to point back to the legacy blog (2) existing disqus comments can't be ported passively (3) there weren't a lot of comments anyway.

If disqus is worth having despite these issues, it can be very easily turned back on (see the commits just above).

**Comment by ranjitjhala** [comment]
Wow that’s awesome! No worries about disqus - fine to ditch imo. Will take
a look and merge this afternoon?

Thank you so much!!

**Comment by yanhasu** [comment]
> Will take a look and merge this afternoon?

Go for it!
I'm not planning to tweak it any more -- future changes can get their own PR.

**Comment by yanhasu** [comment]
@ranjitjhala are there any changes that I should make?

**Comment by ranjitjhala** [comment]
Oops -- sorry, thanks for bumping! Two things:

1. `docs/mkDocs/README.md` is the latest instructions for how to rebuild, yes?
2. I should be able to change the font/style just by tweaking the mkDocs theme? 

I may want to change the theme currently at `https://yanhasu.github.io/liquidhaskell` 
e.g. to make the white-on-turquoise easier to read etc.

Thanks so much again!

**Comment by yanhasu** [comment]
>     1. `docs/mkDocs/README.md` is the latest instructions for how to rebuild, yes?

Yes.
I've only tested the instructions on my fork (not the main repo), but I see no reason why they shouldn't work in the main repo too (all the links point to the main repo, in any case).

>     2. I should be able to change the font/style just by tweaking the mkDocs theme?
> 
> I may want to change the theme currently at `https://yanhasu.github.io/liquidhaskell`
> e.g. to make the white-on-turquoise easier to read etc.

The main customisation points are:
* `docs/mkDocs/mkdocs.yml` -- the top-level config file, for `mkdocs`-supported configuration (navbar content, plugins etc.)
* `docs/mkDocs/docs/static/misc.css` -- general styling that  `mkdocs` doesn't have built-in options for
* `docs/mkDocs/docs/theme-overrides/` -- for heavy duty HTML templating (e.g. I used it to add dates to the blog posts)

For fonts and theme I'd first look at `mkdocs.yml`, then `misc.css`.
(`liquid-light.css` might also play a role -- I pulled it in wholesale from the old blog to style the code snippets)

**Comment by yanhasu** [comment]
@ranjitjhala currently the docs source code is merged but the docs are not [deployed](https://ucsd-progsys.github.io/liquidhaskell/) -- is this intentional?

We don't have CI set up for the docs (yet), so a manual `mkdocs gh-deploy` is needed whenever changes get merged.

**Comment by ranjitjhala** [comment]
super let me merge!

**Pull request merged**
