### PR TITLE
dependent pairs

### PR DESCRIPTION
**Pull request by nikivazou**
Syntactic sugar for dependent pairs (without explicitely using Abstract Refinements)

### CODE REVIEW

**Comment by ranjitjhala** [comment]
What is the motivation here, that the abs-ref syntax is a bit heavyweight for this common use case? Or something else? At any rate, please add documentation to README?

**Comment by nikivazou** [comment]
Exactly! 

In my example `(x::Int, {v:Int | x <= v})` is more natural than its desugar `(Int, Int)<\x -> {v:Int | x <= v}>`

**Comment by ranjitjhala** [comment]
Cool, does this work for, say, triples?

**Comment by nikivazou** [comment]
@ranjitjhala it works for triples etc
 I did not special case pairs and again, it is just parsing syntactic sugar!

**Pull request merged**
