### PR TITLE
Infix Operators in the logic

### PR DESCRIPTION
**Pull request by nikivazou**
Infix operators can be defined in the logic using a Haskell like notation

     {-@ infixl 9 <> @-}

Addresses issue #819

### CODE REVIEW

**Comment by ranjitjhala** [comment]
I don't believe this :) (bravo!!!)

**Comment by nikivazou** [comment]
And it does not break things:) 

May I merge?

**Comment by ranjitjhala** [comment]
(Assuming all tests pass) yes

**Comment by gridaphobe** [comment]
Is it possible to seed the fixity table with the fixities that GHC already knows about?

**Comment by nikivazou** [comment]
I used this 
https://www.haskell.org/onlinereport/decls.html#fixity

Other than that, by "buld-in" Liquid Haskell does not defined any other infix ops.

**Pull request merged**
