### PR TITLE
Nomeet

### PR DESCRIPTION
**Pull request by ranjitjhala**
`nomeet` replaces `strengthenS` for `strengthen` in the definition
of `varRefType`. 

@nikivazou Why does `tests/neg/strata.hs` fail EVEN if I just replace
 the `otherwise` case? The fq file holds no answers -- because even 
in `master` the generated .fq file is SAT?

(Anyways, I'd like to merge this ASAP once we can resolve the issue with strata.hs)

### CODE REVIEW

**Comment by ranjitjhala** [comment]
Sorry, I *should* have split into 2 PR, since the other major edits are just updating the ICFP tests to work with GHC 710.

**Comment by nikivazou** [comment]
I want to look into that, but I cannot build it. Should I use ghc 7.10?

**Comment by spinda** [comment]
What build error are you seeing?

**Comment by nikivazou** [comment]
It does not know Data.Monoid.
I get things like

    Not in scope: ‘mempty’

On Fri, Jun 26, 2015 at 11:31 AM, Michael Smith <notifications@github.com>
wrote:

> What build error are you seeing?
>
> On Fri, Jun 26, 2015, 11:17 Niki Vazou <notifications@github.com> wrote:
>
> > I want to look into that, but I cannot build it. Should I use ghc 7.10?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/ucsd-progsys/liquidhaskell/pull/410#issuecomment-115822741
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquidhaskell/pull/410#issuecomment-115826047>
> .
>



-- 
Niki Vazou

**Comment by spinda** [comment]
Which module is that in? Can you paste the error message?

**Comment by gridaphobe** [comment]
This is due to the new Prelude in 7.10, which re-exports a number of new types and functions, e.g. from Data.Monoid, Data.Foldable, Control.Applicative, etc.

@nikivazou Just add the necessary imports and push them, we want to be compatible with 7.8 and 7.10 :)

**Comment by nikivazou** [comment]
Ok, just fixed it. It conditionally added the required imports. I.e.

#if __GLASGOW_HASKELL__ < 710
import           Data.Monoid      (mconcat, mempty)
import           Control.Applicative ((<$>))
#endif


On Fri, Jun 26, 2015 at 11:57 AM, Eric Seidel <notifications@github.com>
wrote:

> This is due to the new Prelude in 7.10, which re-exports a number of new
> types and functions, e.g. from Data.Monoid, Data.Foldable,
> Control.Applicative, etc.
>
> @nikivazou <https://github.com/nikivazou> Just add the necessary imports
> and push them, we want to be compatible with 7.8 and 7.10 :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquidhaskell/pull/410#issuecomment-115833962>
> .
>



-- 
Niki Vazou

**Comment by gridaphobe** [comment]
@nikivazou no need for the CPP :)

**Comment by nikivazou** [comment]
I need it at 7.8

On Fri, Jun 26, 2015 at 11:59 AM, Eric Seidel <notifications@github.com>
wrote:

> @nikivazou <https://github.com/nikivazou> no need for the CPP :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquidhaskell/pull/410#issuecomment-115835592>
> .
>



-- 
Niki Vazou

**Comment by gridaphobe** [comment]
I mean, just add the imports *unconditionally*

**Comment by nikivazou** [comment]
But then it does not work for 7.10

On Fri, Jun 26, 2015 at 12:01 PM, Eric Seidel <notifications@github.com>
wrote:

> I mean, just add the imports *unconditionally*
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquidhaskell/pull/410#issuecomment-115836890>
> .
>



-- 
Niki Vazou

**Comment by gridaphobe** [comment]
It does! Prelude just re-exports the functions.

**Comment by nikivazou** [comment]
Oh, maybe then there was a warning and due to our -W flag we made it into
an error.

On Fri, Jun 26, 2015 at 12:04 PM, Eric Seidel <notifications@github.com>
wrote:

> It does! Prelude just re-exports the functions.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquidhaskell/pull/410#issuecomment-115838828>
> .
>



-- 
Niki Vazou

**Comment by gridaphobe** [comment]
Hrm, I explicitly disabled those warnings..

https://github.com/ucsd-progsys/liquidhaskell/blob/master/liquidhaskell.cabal#L248

**Comment by nikivazou** [comment]
I still do not have access to 7.10 so I am not sure exactly why these
imports were erased.

But now it builds again!

On Fri, Jun 26, 2015 at 12:06 PM, Eric Seidel <notifications@github.com>
wrote:

> Hrm, I explicitly disabled those warnings..
>
>
> https://github.com/ucsd-progsys/liquidhaskell/blob/master/liquidhaskell.cabal#L248
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquidhaskell/pull/410#issuecomment-115840736>
> .
>



-- 
Niki Vazou

**Comment by ranjitjhala** [comment]
@spinda are you available for a quick online chat now?

On Fri, Jun 26, 2015 at 12:03 PM, Niki Vazou <notifications@github.com>
wrote:

> But then it does not work for 7.10
>
> On Fri, Jun 26, 2015 at 12:01 PM, Eric Seidel <notifications@github.com>
> wrote:
>
> > I mean, just add the imports *unconditionally*
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/ucsd-progsys/liquidhaskell/pull/410#issuecomment-115836890
> >
>
> > .
> >
>
>
>
> --
> Niki Vazou
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquidhaskell/pull/410#issuecomment-115838283>
> .
>



-- 
Ranjit.

**Comment by spinda** [comment]
Unfortunately not, sorry -- I'm currently up in the mountains on the road
toward Yosemite, with a spotty internet connection. I'll be there for the
weekend -- still working, but I may not be as reachable as usual.

**Comment by spinda** [comment]
Can we try email, if that's okay?

**Comment by ranjitjhala** [comment]
haha, no worries -- just wanted to ask you about stack, can wait till next
week! Have a fun trip! :)
​

**Comment by ranjitjhala** [comment]
All tests pass on 7.10. Merging.

**Pull request merged**
