### PR TITLE
Liquid desugar ghc 8

### PR DESCRIPTION
**Pull request by nikivazou**

### CODE REVIEW

**Comment by gridaphobe** [comment]
Wow, that was quick!

**Comment by nikivazou** [comment]
I had it while moving to ghc-8, but then just removed it because I thought we do not need it. 

Still Travis likes NOTHING.

**Comment by gridaphobe** [comment]
ping @atondwal, seems like your hack ought to help?

**Comment by atondwal** [comment]
Hmm git seems to be getting the object, but isn't realizing that it's a commit for some reason. Try adding a dummy commit to desugar and updating the submodule commit?

**Pull request merged**
