### PR TITLE
More parser cleanup

### PR DESCRIPTION
**Pull request by alanz**
Left factoring the `forall` and data declaration parsing.

### CODE REVIEW

**Comment by ranjitjhala** [comment]
👍 thanks!!!

**Comment by nikivazou** [comment]
Hey @alanz how do I run just the parsing tests?
I tried the following but failed

```
stack test liquidhaskell-parser
The following target packages were not found: liquidhaskell-parser
```

**Comment by alanz** [comment]
stack test liquidhaskell:liquidhaskell-parser

**Comment by nikivazou** [comment]
Thanks!

I am upgrading to ghc-8 and have messed up with name resolution. 
Getting the following parsing error 

```
    default parser (Asrts):                                        FAIL
      expected: "Asrts ([\"assumeIndices\" (dummyLoc)],(t:ByteStringNE -> s:ByteString -> [(OkPos t s)] (dummyLoc),Nothing))"
       but got: "Asrts ([\"assumeIndices\" (dummyLoc)],(t:ByteStringNE -> s:BS.ByteString -> [(OkPos t s)] (dummyLoc),Nothing))"
```

Do you have any idea?

**Comment by alanz** [comment]
The only difference is the qualification of the ByteString, which is a
pretty printer artifact.

So updating the test should be fine.

But you may need CPP for the older compilers.

**Pull request merged**
