### PR TITLE
Fix word8 spec

### PR DESCRIPTION
**Pull request by themattchan**
Fixes a missing import in `Word8.spec` leading to this failure:

```
**** RESULT: ERROR *************************************************************


 /Users/mattchan/packet-analysis/.stack-work/install/x86_64-osx/lts-6.4/7.10.3/share/x86_64-osx-ghc-7.10.3/liquidhaskell-0.6.0.0/include/Data/Word8.spec:3:14: Error: GHC Error

 3 | invariant {v:Word8 | 0 <= v }
                  ^

     Not in scope: type constructor or class `Word8'
```

### CODE REVIEW

**Comment by ranjitjhala** [comment]
Thanks Matt! 

Looks like the build is broken due to some silly submodule hassles. 

@themattchan can you do the following in your repo:

```
git fetch origin
git merge develop
```

and then update the PR?

**Comment by ranjitjhala** [comment]
I just did 

``` 
$ git submodule status
 d7c36afd5a4f6f5702c2e18e84545d8d029485f2 benchmarks/xmonad (heads/master)
 d34fc00f9790c888e3c3b1c1708fe8f4133416c5 liquid-fixpoint (liquid-fixpoint-0.5.0.1-303-gd34fc00)
 a9be047a996b3a4aa76910494804e6b6565a0707 prover (heads/develop)
```

That is, the hashes in your commit must be old/wrong ones.

**Comment by themattchan** [comment]
@ranjitjhala should work now... but it turns out that this PR doesn't fix that error :(

**Comment by themattchan** [comment]
Now fixed. Thanks @nikivazou!

**Comment by nikivazou** [comment]
Thanks @themattchan!

**Comment by ranjitjhala** [comment]
Thanks Matt and Niki!

**Pull request merged**
